load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_shared_library", "rust_test")

EXTENSION_FEATURES = ["static"]

rust_library(name = "turso_ext_tests", srcs = glob(["src/**/*.rs"]), aliases = aliases(), crate_features = EXTENSION_FEATURES, crate_root = "src/lib.rs", deps = ["//extensions/core:turso_ext"] + all_crate_deps(normal = True), edition = crate_edition(), visibility = ["//visibility:public"])

rust_shared_library(name = "turso_ext_tests_cdylib", srcs = glob(["src/**/*.rs"]), aliases = aliases(), crate_features = EXTENSION_FEATURES, crate_name = "turso_ext_tests", crate_root = "src/lib.rs", deps = ["//extensions/core:turso_ext"] + all_crate_deps(normal = True), edition = crate_edition())

rust_test(name = "turso_ext_tests_test", crate = ":turso_ext_tests", crate_features = EXTENSION_FEATURES, aliases = aliases(normal_dev = True), deps = all_crate_deps(normal_dev = True))
