#!/bin/bash

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/../../.." && pwd )"

# Navigate to the wasm directory
cd "$PROJECT_ROOT/bindings/wasm/integration-tests" || exit 1

npm run test