load("//tools/bazel:rust.bzl", "turso_cargo_build_script", "turso_rust_library", "turso_rust_shared_library", "turso_rust_test")

EXTENSION_FEATURES = ["static"]

turso_cargo_build_script()

turso_rust_library(
    name = "limbo_ipaddr",
    crate_features = EXTENSION_FEATURES,
    visibility = ["//visibility:public"],
    deps = [
        ":build_script",
        "//extensions/core:turso_ext",
    ],
)

turso_rust_shared_library(
    name = "limbo_ipaddr_cdylib",
    srcs = glob(["src/**/*.rs"]),
    crate_features = EXTENSION_FEATURES,
    crate_name = "limbo_ipaddr",
    crate_root = "src/lib.rs",
    deps = [
        ":build_script",
        "//extensions/core:turso_ext",
    ],
)

turso_rust_test(
    name = "limbo_ipaddr_test",
    cargo_proc_macro_deps = [],
    crate = ":limbo_ipaddr",
    crate_features = EXTENSION_FEATURES,
)
