#!/bin/sh

run_test() {
  test="$1"
  db="$test.db"
  rm -f "$db"
  sqlite3 "$db" < "$test-create.sql"
  ./database-cmp "$db" "$(cat $test-check.sql)"
  echo "$test: ok"
}

run_test "test-btree-depth"
run_test "test-freelist"
run_test "test-large-db"
run_test "test-overflow-page"
run_test "test-pagesize-512"
run_test "test-pagesize-65536"
run_test "test-types"
