load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//cargo:defs.bzl", "cargo_build_script")
load("@rules_rust//rust:defs.bzl", "rust_shared_library")

SYNC_JS_FEATURES = []

cargo_build_script(name = "build_script", srcs = ["build.rs"], aliases = aliases(build = True), crate_root = "build.rs", deps = all_crate_deps(build = True), edition = crate_edition())

rust_shared_library(
    name = "turso_sync_js_cdylib",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    crate_features = SYNC_JS_FEATURES,
    crate_name = "turso_sync_js",
    crate_root = "src/lib.rs",
    deps = [":build_script", "//bindings/javascript:turso_node", "//core:turso_core", "//sync/engine:turso_sync_engine"] + all_crate_deps(normal = True),
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)
