load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_test(
    name = "run_rust_tests_test",
    srcs = ["run_rust_tests_test.sh"],
    args = ["$(rootpath :run_rust_tests.sh)"],
    data = ["run_rust_tests.sh"],
)

exports_files([
    "napi_build_wasi_link.patch",
    "rules_rust_wasip1_threads.patch",
    "rules_rust_windows_dependency_argfiles.patch",
    "rules_rust_windows_dependency_paths.patch",
    "run_rust_tests.sh",
])
