FROM lukemathwalker/cargo-chef:latest-rust-1.88.0 AS chef
RUN apt update \
    && apt install -y git libssl-dev pkg-config\
    && apt clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

#
# Cache dependencies
#

FROM chef AS planner
RUN --mount=type=bind,source=.,target=/app \
    cargo chef prepare --bin limbo_sim --recipe-path /tmp/recipe.json

#
# Build the project.
#

FROM chef AS builder 

COPY --from=planner /tmp/recipe.json recipe.json
RUN cargo chef cook --bin limbo_sim --release --recipe-path recipe.json
COPY . .

RUN cargo build --bin limbo_sim --release

#
# The final image.
#

FROM debian:bookworm-slim AS runtime
# Install Bun (we want to use a fancy shell so we can e.g. post github issues when simulator fails)
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    ca-certificates \
    libssl3 \
    openssl \
    && curl -fsSL https://bun.sh/install | bash \
    && ln -s /root/.bun/bin/bun /usr/local/bin/bun \
    && rm -rf /var/lib/apt/lists/*

# Accept git hash as build argument
ARG GIT_HASH
ENV GIT_HASH=${GIT_HASH:-unknown}

WORKDIR /app
COPY --from=builder /app/target/release/limbo_sim /app/limbo_sim
COPY testing/simulator/simulator-docker-runner/package.json testing/simulator/simulator-docker-runner/bun.lock testing/simulator/simulator-docker-runner/tsconfig.json ./
RUN bun install
COPY testing/simulator/simulator-docker-runner/* ./

RUN chmod +x /app/docker-entrypoint.simulator.ts
RUN chmod +x /app/limbo_sim

ENTRYPOINT ["bun", "/app/docker-entrypoint.simulator.ts"]
# Arguments can be passed at runtime
CMD []
