/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A database opened with the PostgreSQL schema dialect. */
export declare class PgDatabase {
  /**
   * Opens the database synchronously. The JS layer calls this off the
   * constructor's synchronous path so open errors reject `waitReady`.
   */
  constructor(path: string, opts?: PgDatabaseOpts | undefined | null)
  get path(): string
  get open(): boolean
  /**
   * Split a SQL string into individual statements (PG-aware: respects
   * strings, comments, and dollar-quoting).
   */
  splitStatements(sql: string): Array<string>
  prepare(sql: string): PgStatement
  /**
   * Run one iteration of the I/O loop; the JS layer calls this while a
   * statement step reports that I/O is pending.
   */
  ioStep(): void
  /** Whether the connection has an open transaction (inverse of autocommit). */
  inTransaction(): boolean
  close(): void
}

/** A prepared statement. */
export declare class PgStatement {
  get numColumns(): number
  /** Result-column metadata with PostgreSQL type OIDs. */
  columns(): Array<PgColumn>
  /**
   * Bind a parameter by PostgreSQL `$N` name (e.g. `"$1"`). The bytecode
   * compiler may assign internal indices in a different order than the $N
   * numbering, so the lookup goes through `parameter_index`; `fallback` is
   * the 1-based position used when the statement has anonymous parameters.
   */
  bindNamed(name: string, fallback: number, value: unknown): void
  /** Step the statement: 1 = row available, 2 = done, 3 = I/O needed. */
  stepSync(): number
  /**
   * The current row as an array of raw values. Integers always come back
   * as BigInt so 64-bit values never lose precision; the JS layer decides
   * number vs bigint per PGlite's int8 rules.
   */
  row(): unknown
  /** Number of rows changed by this statement. */
  nChange(): number
  reset(): void
  finalize(): void
}

export interface PgColumn {
  name: string
  dataTypeId: number
}

export interface PgDatabaseOpts {
  readonly?: boolean
  fileMustExist?: boolean
  timeout?: number
  defaultQueryTimeout?: number
}
