#!/usr/bin/env python3
"""Generate MBT trace fixtures from checkpoint.qnt for the Rust adapter.

Runs `quint run --mbt` over several seeds, then transpiles each ITF trace into a
trivial line format (no JSON dependency in the Rust test):

    TRACE
    <action> <committed-id>...      # committed set AFTER this step
    ...

Output: ../../../core/mvcc/database/mbt_traces.mbt (next to the adapter test, so
it can be include_str!'d; `.mbt` rather than `.txt` because the repo globally
ignores `**/*.txt`). Re-run after changing checkpoint.qnt.

    python3 mbt_gen.py
"""
import json
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC = os.path.join(HERE, "checkpoint.qnt")
OUT = os.path.normpath(os.path.join(HERE, "../../../core/mvcc/database/mbt_traces.mbt"))
SEEDS = list(range(1, 41))
MAX_STEPS = 100


def resolve(committed_set):
    """Resolve a Set[Op] (the spec's `committed`) to the live (key, value)
    contents: latest ts per key wins; a tombstone (`del`) drops the key."""
    by_key = {}
    for op in committed_set["#set"]:
        k = int(op["key"]["#bigint"])
        ts = int(op["ts"]["#bigint"])
        v = int(op["value"]["#bigint"])
        deleted = bool(op["del"])
        if k not in by_key or ts > by_key[k][0]:
            by_key[k] = (ts, v, deleted)
    return sorted((k, v) for k, (_ts, v, deleted) in by_key.items() if not deleted)


def gen_trace(seed: int):
    with tempfile.NamedTemporaryFile(suffix=".itf.json", delete=False) as f:
        itf = f.name
    subprocess.run(
        ["quint", "run", SPEC, "--mbt", "--out-itf", itf,
         "--max-steps", str(MAX_STEPS), "--max-samples", "1", "--seed", hex(seed)],
        check=True, capture_output=True, cwd=HERE,
    )
    with open(itf) as f:
        d = json.load(f)
    os.unlink(itf)
    lines = []
    for st in d["states"]:
        action = st["mbt::actionTaken"]
        # The `seed` pre-populate step is just a large atomic commit; emit it as a
        # `commit` so the adapter replays it as one insert txn (it reconstructs the
        # rows by diffing contents — the action name only selects commit-vs-ckpt).
        if action == "seed":
            action = "commit"
        # Tag the checkpoint's mode onto its start action so the adapter replays
        # the right CheckpointMode (passive/full/restart/truncate).
        if action == "checkpointStart":
            action = f"checkpointStart:{st['ckptMode']}"
        contents = resolve(st["committed"])
        lines.append(" ".join([action] + [f"{k}:{v}" for k, v in contents]))
    return lines


def main():
    blocks = []
    for seed in SEEDS:
        try:
            blocks.append(gen_trace(seed))
        except subprocess.CalledProcessError as e:
            print(f"quint failed for seed {seed}: {e.stderr.decode()}", file=sys.stderr)
            sys.exit(1)
    with open(OUT, "w") as f:
        f.write("# Generated by docs/internals/mvcc/mbt_gen.py from checkpoint.qnt.\n")
        f.write("# Do not edit by hand. Each TRACE block: `<action> <committed-id>...`\n")
        f.write("# (committed set after the step). Replayed by the Rust MBT adapter.\n")
        for b in blocks:
            f.write("TRACE\n")
            for line in b:
                f.write(line + "\n")
    print(f"wrote {len(blocks)} traces to {OUT}")


if __name__ == "__main__":
    main()
