use crate::common::{ExecRows, TempDatabase};

const LEGACY_FIXTURE: &str = "integration/fixtures/legacy_unicode_lowercased_table.db";

fn open_legacy_fixture(filename: &str) -> (tempfile::TempDir, std::path::PathBuf) {
    let fixture = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(LEGACY_FIXTURE);
    let tmp = tempfile::TempDir::new().unwrap();
    let path = tmp.path().join(filename);
    std::fs::copy(&fixture, &path).expect("copy fixture db");
    (tmp, path)
}

/// Regression test for https://github.com/tursodatabase/turso/issues/5730 (and #5781).
///
/// `fixtures/legacy_unicode_lowercased_table.db` was generated by a pre-fix Turso version that
/// folded identifiers with Unicode lowercasing. It contains two tables created as `MyTable`
/// (ASCII) and `CŒur` (non-ASCII), both persisted with a lowercased `name`/`tbl_name` in
/// sqlite_schema (`mytable`, `cœur`) while the `sql` column kept the original case. Opening that
/// database now must keep both tables addressable by their original case, and DROP must remove
/// the rows cleanly (a non-ASCII table previously orphaned its row, corrupting the schema on
/// reopen).
#[test]
fn drop_tables_from_legacy_unicode_lowercased_db() {
    let (_tmp, path) = open_legacy_fixture("legacy.db");

    let db = TempDatabase::new_with_existent(&path);
    let conn = db.connect_limbo();

    // sqlite_schema still shows the Unicode-lowercased names physically stored on disk.
    let names: Vec<(String,)> =
        conn.exec_rows("SELECT name FROM sqlite_schema WHERE type = 'table' ORDER BY name");
    assert_eq!(names, vec![("cœur".to_string(),), ("mytable".to_string(),)]);

    // Both tables resolve by their original case (ASCII and non-ASCII) and by the lowercased name.
    let ascii_orig: Vec<(i64,)> = conn.exec_rows("SELECT Col1 FROM MyTable");
    assert_eq!(ascii_orig, vec![(10,)]);
    let nonascii_orig: Vec<(i64,)> = conn.exec_rows("SELECT x FROM CŒur");
    assert_eq!(nonascii_orig, vec![(1,)]);
    let nonascii_lower: Vec<(i64,)> = conn.exec_rows("SELECT x FROM cœur");
    assert_eq!(nonascii_lower, vec![(1,)]);

    // DROP by the original case must remove each row cleanly.
    conn.execute("DROP TABLE MyTable").unwrap();
    conn.execute("DROP TABLE CŒur").unwrap();
    let count: Vec<(i64,)> = conn.exec_rows("SELECT count(*) FROM sqlite_schema");
    assert_eq!(count, vec![(0,)]);

    // Reopen and confirm no orphaned schema row remained (which used to corrupt the db).
    drop(conn);
    let db = TempDatabase::new_with_existent(&path);
    let conn = db.connect_limbo();
    let integrity: Vec<(String,)> = conn.exec_rows("PRAGMA integrity_check");
    assert_eq!(integrity, vec![("ok".to_string(),)]);
}

/// Bug 1: CREATE INDEX on a table loaded from a legacy (Unicode-lowercased) DB must key the
/// index under the same map slot as the table, so subsequent INSERTs find the index cursor and
/// the index's root page is actually used.
#[test]
fn create_index_on_legacy_unicode_table() {
    let (_tmp, path) = open_legacy_fixture("legacy.db");
    let db = TempDatabase::new_with_existent(&path);
    let conn = db.connect_limbo();

    conn.execute("CREATE INDEX myidx ON CŒur(x)").unwrap();
    // INSERT must not panic with "no cursor found for index" — the in-memory index
    // must be reachable through the table's stored key.
    conn.execute("INSERT INTO CŒur VALUES(7)").unwrap();

    let xs: Vec<(i64,)> = conn.exec_rows("SELECT x FROM CŒur ORDER BY x");
    assert_eq!(xs, vec![(1,), (7,)]);

    // Reopen and verify integrity: the index page must be live, not orphaned ("Page N: never used").
    drop(conn);
    let db = TempDatabase::new_with_existent(&path);
    let conn = db.connect_limbo();
    let integrity: Vec<(String,)> = conn.exec_rows("PRAGMA integrity_check");
    assert_eq!(integrity, vec![("ok".to_string(),)]);
}

/// Bug 2: DROP TABLE of a legacy-aliased table that has an index must remove both rows from
/// sqlite_schema. Previously the index row's `tbl_name` mismatched (NOCASE doesn't fold `Œ`),
/// leaving an orphan row that corrupted the schema on reopen.
#[test]
fn drop_legacy_unicode_table_with_index() {
    let (_tmp, path) = open_legacy_fixture("legacy.db");
    let db = TempDatabase::new_with_existent(&path);
    let conn = db.connect_limbo();

    conn.execute("CREATE INDEX myidx ON CŒur(x)").unwrap();
    conn.execute("DROP TABLE CŒur").unwrap();

    // No sqlite_schema rows should reference the dropped table or index.
    let rows: Vec<(String, String)> = conn.exec_rows(
        "SELECT type, name FROM sqlite_schema WHERE tbl_name LIKE '%œur' OR tbl_name LIKE '%Œur' OR name = 'myidx'",
    );
    assert!(
        rows.is_empty(),
        "DROP TABLE left orphan rows in sqlite_schema: {rows:?}"
    );

    // Reopen and confirm clean integrity.
    drop(conn);
    let db = TempDatabase::new_with_existent(&path);
    let conn = db.connect_limbo();
    let integrity: Vec<(String,)> = conn.exec_rows("PRAGMA integrity_check");
    assert_eq!(integrity, vec![("ok".to_string(),)]);
}

/// Bug 3: ALTER TABLE ... RENAME of a legacy-aliased table must not panic. The rename insn
/// previously used raw `normalize_ident` on the typed name, which did not match the stored key
/// for a Unicode-lowercased table, and the `.expect()` blew up.
#[test]
fn alter_rename_legacy_unicode_table() {
    let (_tmp, path) = open_legacy_fixture("legacy.db");
    let db = TempDatabase::new_with_existent(&path);
    let conn = db.connect_limbo();

    conn.execute("ALTER TABLE CŒur RENAME TO Heart").unwrap();

    // New name is queryable, old name is gone.
    let xs: Vec<(i64,)> = conn.exec_rows("SELECT x FROM Heart");
    assert_eq!(xs, vec![(1,)]);

    // Reopen: integrity intact, the new name persists.
    drop(conn);
    let db = TempDatabase::new_with_existent(&path);
    let conn = db.connect_limbo();
    let integrity: Vec<(String,)> = conn.exec_rows("PRAGMA integrity_check");
    assert_eq!(integrity, vec![("ok".to_string(),)]);
    let xs: Vec<(i64,)> = conn.exec_rows("SELECT x FROM Heart");
    assert_eq!(xs, vec![(1,)]);
}

/// Bug 4: AUTOINCREMENT must write the original-case table name into sqlite_sequence, matching
/// SQLite and the original-case preservation goal of the PR. Previously the bytecode used the
/// normalized in-memory name and stored e.g. `mytbl` instead of `MyTbl`.
#[test]
fn sqlite_sequence_preserves_original_case() {
    let tmp = tempfile::TempDir::new().unwrap();
    let path = tmp.path().join("seq.db");
    let db = TempDatabase::new_with_existent(&path);
    let conn = db.connect_limbo();

    conn.execute("CREATE TABLE MyTbl(id INTEGER PRIMARY KEY AUTOINCREMENT, x)")
        .unwrap();
    conn.execute("INSERT INTO MyTbl(x) VALUES(1)").unwrap();

    let names: Vec<(String,)> = conn.exec_rows("SELECT name FROM sqlite_sequence");
    assert_eq!(names, vec![("MyTbl".to_string(),)]);
}

/// Bug 5: A name that ASCII-folds to a string distinct from the legacy-aliased key must remain
/// creatable. The legacy alias maps the original-case ASCII fold (e.g. `cŒur`) to the stored
/// Unicode-lowercased key (`cœur`), but a sibling identifier like `CŒUR` ASCII-folds to a
/// different string and is a legitimately distinct table under ASCII-only folding (SQLite allows
/// both to coexist).
#[test]
fn legacy_alias_does_not_block_distinct_identifier() {
    let (_tmp, path) = open_legacy_fixture("legacy.db");
    let db = TempDatabase::new_with_existent(&path);
    let conn = db.connect_limbo();

    // ASCII-fold of `CŒUR` is `cŒur`; ASCII-fold of `cœur` (the stored legacy name) is itself —
    // those strings differ (`Œ` ≠ `œ` under ASCII-only folding), so the two tables are distinct
    // under the PR's identifier semantics. The legacy table stays reachable by names whose ASCII
    // fold is `cœur` (e.g. `cœUR`), while the new table claims the `cŒur` slot.
    conn.execute("CREATE TABLE CŒUR(z)").unwrap();
    conn.execute("INSERT INTO CŒUR VALUES(42)").unwrap();
    conn.execute("INSERT INTO cœUR VALUES(99)").unwrap();

    let new_rows: Vec<(i64,)> = conn.exec_rows("SELECT z FROM CŒUR");
    assert_eq!(new_rows, vec![(42,)]);
    let legacy_rows: Vec<(i64,)> = conn.exec_rows("SELECT x FROM cœur ORDER BY x");
    assert_eq!(legacy_rows, vec![(1,), (99,)]);

    drop(conn);
    let db = TempDatabase::new_with_existent(&path);
    let conn = db.connect_limbo();
    let integrity: Vec<(String,)> = conn.exec_rows("PRAGMA integrity_check");
    assert_eq!(integrity, vec![("ok".to_string(),)]);
}
