//! Utilities for manipulating AST expressions.

use turso_parser::ast::{self, Name};

/// Recursively rename column references in an AST expression.
/// This is needed when a column is renamed via ALTER TABLE RENAME COLUMN,
/// as generated column expressions that reference the old name must be updated.
pub fn rename_column_in_expr(expr: &mut ast::Expr, old_name: &str, new_name: &str) {
    match expr {
        ast::Expr::Id(name) if name.as_str().eq_ignore_ascii_case(old_name) => {
            *name = Name::from_string(new_name);
        }
        ast::Expr::Name(name) if name.as_str().eq_ignore_ascii_case(old_name) => {
            *name = Name::from_string(new_name);
        }
        ast::Expr::Qualified(_, col_name) if col_name.as_str().eq_ignore_ascii_case(old_name) => {
            *col_name = Name::from_string(new_name);
        }
        ast::Expr::Binary(lhs, _, rhs) => {
            rename_column_in_expr(lhs, old_name, new_name);
            rename_column_in_expr(rhs, old_name, new_name);
        }
        ast::Expr::Unary(_, inner) => {
            rename_column_in_expr(inner, old_name, new_name);
        }
        ast::Expr::Parenthesized(exprs) => {
            for e in exprs {
                rename_column_in_expr(e, old_name, new_name);
            }
        }
        ast::Expr::Cast { expr: inner, .. } => {
            rename_column_in_expr(inner, old_name, new_name);
        }
        // Other expression types don't contain column references or are not
        // generated by the simulator's expression generator
        _ => {}
    }
}
