// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'connection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<RustConnection> connect({required ConnectArgs args}) =>
    RustLib.instance.api.crateApiConnectConnect(args: args);

/// Supported encryption ciphers for local database encryption.
enum EncryptionCipher {
  aes128Gcm,
  aes256Gcm,
  aegis256,
  aegis256x2,
  aegis128l,
  aegis128x2,
  aegis128x4,
}

/// Encryption options for local database encryption.
class EncryptionOpts {
  /// The cipher to use for encryption
  final EncryptionCipher cipher;

  /// The hex-encoded encryption key
  final String hexkey;

  const EncryptionOpts({
    required this.cipher,
    required this.hexkey,
  });

  @override
  int get hashCode => cipher.hashCode ^ hexkey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptionOpts &&
          runtimeType == other.runtimeType &&
          cipher == other.cipher &&
          hexkey == other.hexkey;
}

class ConnectArgs {
  final String url;
  final String? authToken;
  final String? syncUrl;
  final BigInt? syncIntervalSeconds;
  final String? encryptionKey;
  final bool? readYourWrites;
  final OpenFlags? openFlags;
  final bool? offline;

  /// Optional encryption options for local database encryption
  final EncryptionOpts? encryption;

  const ConnectArgs({
    required this.url,
    this.authToken,
    this.syncUrl,
    this.syncIntervalSeconds,
    this.encryptionKey,
    this.readYourWrites,
    this.openFlags,
    this.offline,
    this.encryption,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      authToken.hashCode ^
      syncUrl.hashCode ^
      syncIntervalSeconds.hashCode ^
      encryptionKey.hashCode ^
      readYourWrites.hashCode ^
      openFlags.hashCode ^
      offline.hashCode ^
      encryption.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectArgs &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          authToken == other.authToken &&
          syncUrl == other.syncUrl &&
          syncIntervalSeconds == other.syncIntervalSeconds &&
          encryptionKey == other.encryptionKey &&
          readYourWrites == other.readYourWrites &&
          openFlags == other.openFlags &&
          offline == other.offline &&
          encryption == other.encryption;
}

enum OpenFlags { readOnly, readWrite, create }
