/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Database {
  constructor(path: string)
  init(): ProtocolNapi
  push(): ProtocolNapi
  pull(): ProtocolNapi
  sync(): ProtocolNapi
  execute(sql: string): Array<Array<string>>
}

export declare class ProtocolNapi {
  next(resume: ProtocolResume): ProtocolYield | null
}

export type ProtocolResume =
  | { type: 'None' }
  | { type: 'Exists', field0: boolean }
  | { type: 'Content', field0?: Array<number> }
  | { type: 'DbInfo', generation: number }
  | { type: 'DbStatus', baton?: string, status: string, generation: number, maxFrameNo: number }
  | { type: 'Err', field0: string }

export type ProtocolYield =
  | { type: 'DbInfo' }
  | { type: 'DbBootstrap', generation: number }
  | { type: 'WalPush', baton?: string, generation: number, startFrame: number, endFrame: number, frames: Array<number> }
  | { type: 'WalPull', generation: number, startFrame: number }
  | { type: 'ExistsFile', path: string }
  | { type: 'ReadFile', path: string }
  | { type: 'WriteFile', path: string, data: Array<number> }
  | { type: 'TruncateFile', path: string, size: number }
  | { type: 'RemoveFile', path: string }
  | { type: 'Continue' }
