load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "sql_generation",
    srcs = glob(["**/*.rs"]),
    aliases = aliases(),
    crate_root = "lib.rs",
    deps = [
        "//core:turso_core",
        "//sqlite/parser:turso_parser",
    ] + all_crate_deps(normal = True),
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],
)

rust_test(
    name = "sql_generation_test",
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    crate = ":sql_generation",
    deps = all_crate_deps(normal_dev = True),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
)
