//! Generates the Rust code of the rule engine from the compiled rule files.
//!
//! The build script runs the generator, so this module uses only the parser
//! and the compiler. The generated code is one function per rule and one
//! dispatch function that tries the rules of an operator in order. A rule
//! function matches the pattern with plain `if` and `let` statements, calls
//! the functions written in Rust directly, and builds the replacement with
//! the runtime of `rules::engine`.

use std::collections::HashMap;
use std::fmt::Write as _;

use super::compiler::Compiled;
use super::parser::{Expr, ExprKind, FuncName, Rule};

const TRUTH_VALUE_TAG: &str = "TruthValue";
const NULL_IS_FALSE_TAG: &str = "NullIsFalse";
const HIGH_PRIORITY_TAG: &str = "HighPriority";
const LOW_PRIORITY_TAG: &str = "LowPriority";
const OP_NAME_FUNCTION: &str = "OpName";

/// The Rust source of the rule dispatch and the rule functions.
pub(crate) fn generate(compiled: &Compiled) -> Result<String, String> {
    let mut out = String::new();
    out.push_str(
        "// Generated by build.rs from the rule files of this directory. Do not edit.\n\n",
    );
    out.push_str("use smallvec::SmallVec;\n\n");

    let mut rule_positions: HashMap<&str, usize> = HashMap::new();
    let mut unique_rules: Vec<&Rule> = Vec::new();
    let mut rules_by_op: Vec<(&str, Vec<usize>)> = Vec::new();
    for rule in &compiled.rules {
        let position = match rule_positions.get(rule.name.as_str()) {
            Some(&position) => position,
            None => {
                unique_rules.push(rule);
                rule_positions.insert(&rule.name, unique_rules.len() - 1);
                unique_rules.len() - 1
            }
        };
        let root = rule.match_pattern.single_name();
        match rules_by_op.iter_mut().find(|(op, _)| *op == root) {
            Some((_, positions)) => positions.push(position),
            None => rules_by_op.push((root, vec![position])),
        }
    }
    for (_, positions) in &mut rules_by_op {
        positions.sort_by_key(|&position| priority(unique_rules[position]));
    }

    out.push_str("impl RuleSet {\n");
    out.push_str(
        "    /// Try the rules of the operator of a node, in the order of the rule files.\n",
    );
    out.push_str(
        "    pub(super) fn apply_rules_of<'a>(\n        &self,\n        ctx: &EngineContext<'_, '_>,\n        node: NodeRef<'a>,\n        op: Op,\n        context: Context,\n    ) -> Result<Option<Found>> {\n",
    );
    out.push_str("        match op {\n");
    for (op, positions) in &rules_by_op {
        writeln!(out, "            Op::{op} => {{").unwrap();
        out.push_str("                let children = node.children();\n");
        out.push_str(
            "                let child_ops: SmallVec<[Option<Op>; 4]> =\n                    children.iter().map(|child| child.op()).collect();\n",
        );
        for &position in positions {
            writeln!(
                out,
                "                if let Some(found) = self.{}(ctx, node, op, &children, &child_ops, context)? {{\n                    return Ok(Some(found));\n                }}",
                rule_function(&unique_rules[position].name)
            )
            .unwrap();
        }
        out.push_str("                Ok(None)\n            }\n");
    }
    out.push_str("            _ => Ok(None),\n        }\n    }\n");

    for rule in &unique_rules {
        let mut gen = Gen {
            compiled,
            rule: &rule.name,
            out: String::new(),
            indent: 2,
            vars: HashMap::new(),
            uses: HashMap::new(),
            temps: 0,
        };
        gen.count_refs(&rule.match_pattern, false);
        gen.count_refs(&rule.replace, true);
        gen.rule(rule)?;
        out.push('\n');
        out.push_str(&gen.out);
    }
    out.push_str("}\n");
    Ok(out)
}

fn priority(rule: &Rule) -> u8 {
    if rule.has_tag(HIGH_PRIORITY_TAG) {
        0
    } else if rule.has_tag(LOW_PRIORITY_TAG) {
        2
    } else {
        1
    }
}

/// `SimplifyTrueAnd` to `simplify_true_and`, and `LenGT` to `len_gt`.
fn snake_case(name: &str) -> String {
    let chars: Vec<char> = name.chars().collect();
    let mut out = String::with_capacity(name.len() + 4);
    for (index, &ch) in chars.iter().enumerate() {
        if ch.is_ascii_uppercase() {
            let after_lower = index > 0 && !chars[index - 1].is_ascii_uppercase();
            let before_lower = index > 0
                && chars[index - 1].is_ascii_uppercase()
                && chars
                    .get(index + 1)
                    .is_some_and(|next| next.is_ascii_lowercase());
            if after_lower || before_lower {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

fn rule_function(name: &str) -> String {
    format!("rule_{}", snake_case(name))
}

fn variable(label: &str) -> String {
    format!("v_{}", snake_case(label))
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum VarKind {
    /// A part of the matched node, held by reference.
    Node,
    /// A value that a function gave, held by value.
    Value,
}

struct Gen<'c> {
    compiled: &'c Compiled,
    rule: &'c str,
    out: String,
    indent: usize,
    vars: HashMap<String, VarKind>,
    /// How many times the replacement still reads a value variable. The
    /// last read moves the value, the others copy it.
    uses: HashMap<String, usize>,
    temps: usize,
}

impl Gen<'_> {
    fn error(&self, text: &str) -> String {
        format!("rule {}: {text}", self.rule)
    }

    fn line(&mut self, text: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn temp(&mut self, hint: &str) -> String {
        self.temps += 1;
        format!("{hint}_{}", self.temps)
    }

    /// Count the reads of value variables in build positions. In a match
    /// pattern, a function reads its plain variable arguments by
    /// reference, so those do not count.
    fn count_refs(&mut self, expr: &Expr, build: bool) {
        match &expr.kind {
            ExprKind::Ref(label) => {
                if build {
                    *self.uses.entry(label.clone()).or_default() += 1;
                }
            }
            ExprKind::Func { name, args } => {
                if let FuncName::Dynamic(name) = name {
                    self.count_refs(name, false);
                }
                for arg in args {
                    self.count_refs(arg, build);
                }
            }
            ExprKind::CustomFunc { args, .. } => {
                for arg in args {
                    if !matches!(arg.kind, ExprKind::Ref(_)) {
                        self.count_refs(arg, true);
                    }
                }
            }
            ExprKind::Let { target, .. } => self.count_refs(target, build),
            ExprKind::And(left, right) => {
                self.count_refs(left, false);
                self.count_refs(right, false);
            }
            ExprKind::Not(input) => self.count_refs(input, false),
            ExprKind::List(items) => {
                for item in items {
                    self.count_refs(item, build);
                }
            }
            ExprKind::Bind { target, .. } => self.count_refs(target, build),
            ExprKind::Name(_)
            | ExprKind::Any
            | ExprKind::Str(_)
            | ExprKind::Number(_)
            | ExprKind::ListAny => {}
        }
    }

    fn rule(&mut self, rule: &Rule) -> Result<(), String> {
        for line in rule.to_string().lines() {
            self.line(&format!("// {line}"));
        }
        self.line(&format!("fn {}<'a>(", rule_function(&rule.name)));
        self.line("    &self,");
        self.line("    ctx: &EngineContext<'_, '_>,");
        self.line("    node: NodeRef<'a>,");
        self.line("    op: Op,");
        self.line("    children: &Children<'a>,");
        self.line("    child_ops: &[Option<Op>],");
        self.line("    context: Context,");
        self.line(") -> Result<Option<Found>> {");
        self.indent += 1;
        let needs_null_is_false = rule.has_tag(NULL_IS_FALSE_TAG);
        if rule.has_tag(TRUTH_VALUE_TAG) || needs_null_is_false {
            self.line("if !context.truth_value {");
            self.line("    return Ok(None);");
            self.line("}");
        }
        if needs_null_is_false {
            self.line("if !context.null_is_false {");
            self.line("    return Ok(None);");
            self.line("}");
        }
        let ExprKind::Func { args, .. } = &rule.match_pattern.kind else {
            return Err(self.error("the match pattern is not an operator"));
        };
        self.match_args(args, "children", Some("child_ops"), "return Ok(None);")?;
        let replacement = self.build(&rule.replace, "context")?;
        let settled = matches!(rule.replace.kind, ExprKind::Func { .. });
        self.line(&format!(
            "Ok(Some(({replacement}, {:?}, {settled})))",
            rule.name
        ));
        self.indent -= 1;
        self.line("}");
        Ok(())
    }

    /// The operators that a pattern name stands for.
    fn ops_of_names(&self, names: &[String]) -> Result<Vec<String>, String> {
        let mut ops = Vec::new();
        for name in names {
            let defines = self.compiled.lookup_matching_defines(name);
            if defines.is_empty() {
                return Err(self.error(&format!("{name} is not an operator or a tag")));
            }
            for define in defines {
                let op = self.compiled.defines[define].name.clone();
                if !ops.contains(&op) {
                    ops.push(op);
                }
            }
        }
        Ok(ops)
    }

    /// Emit the matching of the argument patterns against the children of
    /// a node. `child_ops` names the operators of the children when they
    /// are known. `fail` is the statement that runs when a pattern does not
    /// match.
    fn match_args(
        &mut self,
        args: &[Expr],
        children: &str,
        child_ops: Option<&str>,
        fail: &str,
    ) -> Result<(), String> {
        for (index, arg) in args.iter().enumerate() {
            if matches!(arg.kind, ExprKind::Any) {
                continue;
            }
            let child = self.temp("child");
            self.line(&format!(
                "let Some(&{child}) = {children}.get({index}) else {{"
            ));
            self.line(&format!("    {fail}"));
            self.line("};");
            let known_op = child_ops.map(|child_ops| format!("{child_ops}[{index}]"));
            self.match_node(arg, &child, known_op.as_deref(), fail)?;
        }
        Ok(())
    }

    /// Emit the matching of a pattern against the node in variable `target`.
    /// `known_op` is an expression that gives the operator of the node, when
    /// the caller has it.
    fn match_node(
        &mut self,
        expr: &Expr,
        target: &str,
        known_op: Option<&str>,
        fail: &str,
    ) -> Result<(), String> {
        match &expr.kind {
            ExprKind::Func {
                name: FuncName::Names(names),
                args,
            } => {
                let ops = self.ops_of_names(names)?;
                let ops: Vec<String> = ops.iter().map(|op| format!("Some(Op::{op})")).collect();
                let op = known_op
                    .map(String::from)
                    .unwrap_or_else(|| format!("{target}.op()"));
                self.line(&format!("if !matches!({op}, {}) {{", ops.join(" | ")));
                self.line(&format!("    {fail}"));
                self.line("}");
                if args.iter().any(|arg| !matches!(arg.kind, ExprKind::Any)) {
                    let children = self.temp("children");
                    self.line(&format!("let {children} = {target}.children();"));
                    self.match_args(args, &children, None, fail)?;
                }
                Ok(())
            }
            ExprKind::Func {
                name: FuncName::Dynamic(_),
                ..
            } => Err(self.error("a match pattern cannot use a dynamic name")),
            ExprKind::CustomFunc { name, args } => {
                let call = self.call(name, args, "context")?;
                self.line(&format!("if !bool_of({:?}, {call})? {{", self.rule));
                self.line(&format!("    {fail}"));
                self.line("}");
                Ok(())
            }
            ExprKind::And(left, right) => {
                self.match_node(left, target, known_op, fail)?;
                self.match_node(right, target, known_op, fail)
            }
            ExprKind::Not(input) => {
                let matched = self.temp("matched");
                let label = self.temp("not");
                self.line(&format!("let {matched} = '{label}: {{"));
                self.indent += 1;
                let vars = self.vars.clone();
                self.match_node(input, target, known_op, &format!("break '{label} false;"))?;
                self.vars = vars;
                self.line("true");
                self.indent -= 1;
                self.line("};");
                self.line(&format!("if {matched} {{"));
                self.line(&format!("    {fail}"));
                self.line("}");
                Ok(())
            }
            ExprKind::List(items) => self.match_list(items, target, fail),
            ExprKind::Bind {
                label,
                target: inner,
            } => {
                self.line(&format!("let {} = {target};", variable(label)));
                self.vars.insert(label.clone(), VarKind::Node);
                self.match_node(inner, target, known_op, fail)
            }
            ExprKind::Let {
                labels,
                target: inner,
                result,
            } => {
                self.bind_let(labels, inner, "context")?;
                self.line(&format!(
                    "if !bool_value({:?}, &{})? {{",
                    self.rule,
                    variable(result)
                ));
                self.line(&format!("    {fail}"));
                self.line("}");
                Ok(())
            }
            ExprKind::Any => Ok(()),
            ExprKind::Str(_)
            | ExprKind::Number(_)
            | ExprKind::Ref(_)
            | ExprKind::Name(_)
            | ExprKind::ListAny => Err(self.error(&format!("{expr} cannot be matched"))),
        }
    }

    fn match_list(&mut self, items: &[Expr], target: &str, fail: &str) -> Result<(), String> {
        let is_any = |item: &Expr| matches!(item.kind, ExprKind::ListAny);
        let len = self.temp("len");
        self.line(&format!("let Some({len}) = {target}.list_len() else {{"));
        self.line(&format!("    {fail}"));
        self.line("};");
        let item_var = self.temp("item");
        let (item, position) = match items {
            [] => {
                self.line(&format!("if {len} != 0 {{"));
                self.line(&format!("    {fail}"));
                self.line("}");
                return Ok(());
            }
            [item] if !is_any(item) => {
                self.line(&format!("if {len} != 1 {{"));
                self.line(&format!("    {fail}"));
                self.line("}");
                (item, "0".to_string())
            }
            [item, rest] if !is_any(item) && is_any(rest) => {
                self.line(&format!("if {len} == 0 {{"));
                self.line(&format!("    {fail}"));
                self.line("}");
                (item, "0".to_string())
            }
            [rest, item] if is_any(rest) && !is_any(item) => {
                self.line(&format!("if {len} == 0 {{"));
                self.line(&format!("    {fail}"));
                self.line("}");
                (item, format!("{len} - 1"))
            }
            [before, item, after] if is_any(before) && is_any(after) && !is_any(item) => {
                return self.match_any_item(item, target, &len, fail);
            }
            _ => return Err(self.error("unsupported list pattern")),
        };
        self.line(&format!(
            "let {item_var} = {target}.list_item({position}).expect(\"checked: the index is less than the length\");"
        ));
        self.match_node(item, &item_var, None, fail)
    }

    /// Emit a loop that finds the first item of a list that matches the
    /// pattern. The variables that the pattern binds are set after the loop.
    fn match_any_item(
        &mut self,
        item: &Expr,
        target: &str,
        len: &str,
        fail: &str,
    ) -> Result<(), String> {
        let mut bound = Vec::new();
        bound_labels(item, &mut bound);
        let holders: Vec<(String, VarKind, String)> = bound
            .iter()
            .map(|(label, kind)| (label.clone(), *kind, self.temp("bound")))
            .collect();
        for (_, kind, holder) in &holders {
            let typ = match kind {
                VarKind::Node => "NodeRef<'a>",
                VarKind::Value => "Value",
            };
            self.line(&format!("let mut {holder}: Option<{typ}> = None;"));
        }
        let found = self.temp("found");
        let index = self.temp("index");
        let item_var = self.temp("item");
        let label = self.temp("item");
        self.line(&format!("let mut {found} = false;"));
        self.line(&format!("for {index} in 0..{len} {{"));
        self.indent += 1;
        self.line(&format!(
            "let {item_var} = {target}.list_item({index}).expect(\"checked: the index is less than the length\");"
        ));
        let matched = self.temp("matched");
        self.line(&format!("let {matched} = '{label}: {{"));
        self.indent += 1;
        let vars = self.vars.clone();
        self.match_node(item, &item_var, None, &format!("break '{label} false;"))?;
        for (bound_label, _, holder) in &holders {
            self.line(&format!("{holder} = Some({});", variable(bound_label)));
        }
        self.vars = vars;
        self.line("true");
        self.indent -= 1;
        self.line("};");
        self.line(&format!("if {matched} {{"));
        self.line(&format!("    {found} = true;"));
        self.line("    break;");
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line(&format!("if !{found} {{"));
        self.line(&format!("    {fail}"));
        self.line("}");
        for (bound_label, kind, holder) in &holders {
            self.line(&format!(
                "let {} = {holder}.expect(\"checked: the item matched\");",
                variable(bound_label)
            ));
            self.vars.insert(bound_label.clone(), *kind);
        }
        Ok(())
    }

    /// Emit a `Let`: call the function and bind its results.
    fn bind_let(&mut self, labels: &[String], target: &Expr, context: &str) -> Result<(), String> {
        let ExprKind::CustomFunc { name, args } = &target.kind else {
            return Err(self.error("a Let must call a function"));
        };
        let call = self.call(name, args, context)?;
        let values = self.temp("values");
        self.line(&format!(
            "let mut {values} = let_values({:?}, {call}, {})?.into_iter();",
            self.rule,
            labels.len()
        ));
        for label in labels {
            self.line(&format!(
                "let {} = {values}.next().expect(\"checked: the function gave enough values\");",
                variable(label)
            ));
            self.vars.insert(label.clone(), VarKind::Value);
        }
        Ok(())
    }

    /// The expression of a call of a function written in Rust. The
    /// arguments that must be built first are built before the call.
    fn call(&mut self, name: &str, args: &[Expr], context: &str) -> Result<String, String> {
        let mut arg_refs = Vec::new();
        for arg in args {
            arg_refs.push(match &arg.kind {
                ExprKind::Ref(label) => match self.var_kind(label)? {
                    VarKind::Node => format!("ArgRef::Node({})", variable(label)),
                    VarKind::Value => format!("ArgRef::Value(&{})", variable(label)),
                },
                ExprKind::Name(name) => format!("ArgRef::Op(Op::{name})"),
                ExprKind::CustomFunc { name, .. } if name == OP_NAME_FUNCTION => {
                    format!("ArgRef::Op({})", self.op_name(arg)?)
                }
                ExprKind::Number(value) => format!("ArgRef::Int({value})"),
                ExprKind::Bind { label, target } => {
                    let value = self.build(target, context)?;
                    self.line(&format!("let {} = {value};", variable(label)));
                    self.vars.insert(label.clone(), VarKind::Value);
                    format!("ArgRef::Value(&{})", variable(label))
                }
                _ => {
                    let value = self.build(arg, context)?;
                    let temp = self.temp("arg");
                    self.line(&format!("let {temp} = {value};"));
                    format!("ArgRef::Value(&{temp})")
                }
            });
        }
        Ok(format!(
            "funcs::{}(ctx, &[{}], {context})?",
            snake_case(name),
            arg_refs.join(", ")
        ))
    }

    fn var_kind(&self, label: &str) -> Result<VarKind, String> {
        self.vars
            .get(label)
            .copied()
            .ok_or_else(|| self.error(&format!("${label} is used before it is bound")))
    }

    /// The expression of the operator that an `(OpName $var)` call gives.
    fn op_name(&mut self, expr: &Expr) -> Result<String, String> {
        let ExprKind::CustomFunc { name, args } = &expr.kind else {
            return Err(self.error("a dynamic name must be an OpName call"));
        };
        if name != OP_NAME_FUNCTION {
            return Err(self.error("a dynamic name must be an OpName call"));
        }
        match args.as_slice() {
            [] => Ok("op".to_string()),
            [arg] => {
                let ExprKind::Ref(label) = &arg.kind else {
                    return Err(self.error("OpName takes one variable"));
                };
                match self.var_kind(label)? {
                    VarKind::Node => Ok(format!("op_of({:?}, {})?", self.rule, variable(label))),
                    VarKind::Value => Err(self.error("OpName takes a variable bound to a node")),
                }
            }
            _ => Err(self.error("OpName takes one variable")),
        }
    }

    /// The expression of a value variable read: the last read moves it.
    fn read_value(&mut self, label: &str) -> String {
        let remaining = self.uses.entry(label.to_string()).or_default();
        *remaining = remaining.saturating_sub(1);
        if *remaining == 0 {
            variable(label)
        } else {
            format!("{}.clone()", variable(label))
        }
    }

    /// Emit the statements that build a replacement, and give the
    /// expression of its value. `context` names the context the value
    /// stands in.
    fn build(&mut self, expr: &Expr, context: &str) -> Result<String, String> {
        match &expr.kind {
            ExprKind::Ref(label) => Ok(match self.var_kind(label)? {
                VarKind::Node => format!("{}.to_value()", variable(label)),
                VarKind::Value => self.read_value(label),
            }),
            ExprKind::Func {
                name: FuncName::Names(names),
                args,
            } => {
                let [name] = names.as_slice() else {
                    return Err(self.error("a constructor has one name"));
                };
                if self.compiled.lookup_define(name).is_none() {
                    return Err(self.error(&format!("{name} is not an operator")));
                }
                self.construct(&format!("Op::{name}"), Some(name == "Case"), args, context)
            }
            ExprKind::Func {
                name: FuncName::Dynamic(name),
                args,
            } => {
                let op = self.op_name(name)?;
                let temp = self.temp("op");
                self.line(&format!("let {temp} = {op};"));
                self.construct(&temp, None, args, context)
            }
            ExprKind::CustomFunc { name, .. } if name == OP_NAME_FUNCTION => {
                Ok(format!("Value::Op({})", self.op_name(expr)?))
            }
            ExprKind::CustomFunc { name, args } => self.call(name, args, context),
            ExprKind::Let {
                labels,
                target,
                result,
            } => {
                self.bind_let(labels, target, context)?;
                Ok(self.read_value(result))
            }
            ExprKind::Name(name) => Ok(format!("Value::Op(Op::{name})")),
            ExprKind::Str(text) => Ok(format!("Value::Str({text:?}.to_string())")),
            ExprKind::Number(_) => {
                Err(self.error("a number can only be an argument of a function"))
            }
            ExprKind::List(items) => {
                let mut parts = Vec::new();
                for item in items {
                    let value = self.build(item, context)?;
                    let temp = self.temp("item");
                    self.line(&format!("let {temp} = {value};"));
                    parts.push(temp);
                }
                Ok(format!("Value::List(vec![{}])", parts.join(", ")))
            }
            ExprKind::Bind { .. }
            | ExprKind::And(..)
            | ExprKind::Not(_)
            | ExprKind::Any
            | ExprKind::ListAny => Err(self.error(&format!("{expr} cannot be built"))),
        }
    }

    /// Emit the building of a node. `is_case` is known for a static
    /// operator; a dynamic operator checks at run time.
    fn construct(
        &mut self,
        op: &str,
        is_case: Option<bool>,
        args: &[Expr],
        context: &str,
    ) -> Result<String, String> {
        let node = self.temp("node");
        let values = format!("{node}_values");
        let whens = format!("{node}_whens");
        self.line(&format!(
            "let mut {values} = Vec::with_capacity({});",
            args.len()
        ));
        let may_be_case = is_case != Some(false);
        if may_be_case {
            self.line(&format!("let mut {whens} = Context::VALUE;"));
        }
        for (index, arg) in args.iter().enumerate() {
            let child_context = format!("{node}_context_{index}");
            match (is_case, index) {
                (Some(true), 1) => self.line(&format!("let {child_context} = {whens};")),
                (None, 1) => self.line(&format!(
                    "let {child_context} = if {op} == Op::Case {{ {whens} }} else {{ nodes::child_context({op}, {index}, {context}) }};"
                )),
                _ => self.line(&format!(
                    "let {child_context} = nodes::child_context({op}, {index}, {context});"
                )),
            }
            let value = self.build(arg, &child_context)?;
            let arg_var = format!("{node}_arg_{index}");
            self.line(&format!("let {arg_var} = {value};"));
            if may_be_case && index == 0 {
                let case_check = match is_case {
                    Some(true) => String::new(),
                    _ => format!("{op} == Op::Case && "),
                };
                self.line(&format!(
                    "if {case_check}matches!({arg_var}, Value::Absent) {{"
                ));
                self.line(&format!("    {whens} = Context::CONDITION;"));
                self.line("}");
            }
            self.line(&format!("{values}.push({arg_var});"));
        }
        self.line(&format!(
            "let {node} = self.build_node(ctx, {op}, {values}, {context})?;"
        ));
        Ok(node)
    }
}

/// The variables that a pattern binds, outside of negated patterns.
fn bound_labels(expr: &Expr, out: &mut Vec<(String, VarKind)>) {
    match &expr.kind {
        ExprKind::Bind { label, target } => {
            out.push((label.clone(), VarKind::Node));
            bound_labels(target, out);
        }
        ExprKind::Let { labels, .. } => {
            for label in labels {
                out.push((label.clone(), VarKind::Value));
            }
        }
        ExprKind::Func { args, .. } => {
            for arg in args {
                bound_labels(arg, out);
            }
        }
        ExprKind::CustomFunc { args, .. } => {
            for arg in args {
                if let ExprKind::Bind { label, .. } = &arg.kind {
                    out.push((label.clone(), VarKind::Value));
                }
            }
        }
        ExprKind::And(left, right) => {
            bound_labels(left, out);
            bound_labels(right, out);
        }
        ExprKind::List(items) => {
            for item in items {
                bound_labels(item, out);
            }
        }
        ExprKind::Not(_)
        | ExprKind::Ref(_)
        | ExprKind::Name(_)
        | ExprKind::Any
        | ExprKind::Str(_)
        | ExprKind::Number(_)
        | ExprKind::ListAny => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::translate::logical::optgen::compile;

    const RULE_FILES: &[(&str, &str)] = &[
        ("ops.opt", include_str!("../rules/ops.opt")),
        ("bool.opt", include_str!("../rules/bool.opt")),
        ("comp.opt", include_str!("../rules/comp.opt")),
        (
            "fold_constants.opt",
            include_str!("../rules/fold_constants.opt"),
        ),
        ("scalar.opt", include_str!("../rules/scalar.opt")),
        ("filter.opt", include_str!("../rules/filter.opt")),
    ];

    #[test]
    fn names_become_snake_case() {
        assert_eq!(snake_case("SimplifyTrueAnd"), "simplify_true_and");
        assert_eq!(snake_case("LenGT"), "len_gt");
        assert_eq!(snake_case("innerLeft"), "inner_left");
        assert_eq!(snake_case("IsNotNull"), "is_not_null");
        assert_eq!(snake_case("GTFoo"), "gt_foo");
    }

    #[test]
    fn the_rule_files_generate_a_function_per_rule() {
        let compiled = compile(RULE_FILES).unwrap_or_else(|errors| panic!("{}", errors.join("\n")));
        let code = generate(&compiled).unwrap();
        for name in [
            "rule_normalize_nested_ands",
            "rule_extract_redundant_conjunct",
            "rule_fold_binary",
            "rule_commute_var",
            "rule_simplify_filter_terms",
            "rule_remove_not_null_condition",
        ] {
            assert!(
                code.contains(&format!("fn {name}<'a>(")),
                "{name} is missing"
            );
        }
        assert_eq!(
            code.matches("fn rule_fold_null_comparison_left<'a>(")
                .count(),
            1
        );
        assert!(code.contains("Op::Eq => {"));
        assert!(code.contains("Op::Filter => {"));
    }
}
