load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_proc_macro")

rust_proc_macro(
    name = "turso_macros",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    crate_root = "src/lib.rs",
    deps = all_crate_deps(normal = True),
    edition = crate_edition(),
    visibility = ["//visibility:public"],
)
