#!/usr/bin/env python3
# /// script
# dependencies = ["matplotlib", "numpy", "scienceplots"]
# ///
"""Draw the TPC-C figures from the benchmark's result files.

Usage: uv run plot-tpcc.py tpmc plot/*-result.csv -o tpmc.png -o tpmc.pdf -o tpmc.tikz
       uv run plot-tpcc.py timeline plot/*-c8-r*-timeline.csv -o timeline-c8.png
       uv run plot-tpcc.py response-time plot/*-c8-r*-hist.csv -o response-time-c8.png

`tpmc` draws the headline number, New-Order transactions per minute (tpmC),
against connections: every result file is one run, runs of the same engine
and connection count make one point, their mean with an error bar of one
standard deviation. tpmC goes on the left axis as solid lines with filled
markers; the CPU the whole process used during the run, as a share of every
hardware thread on the machine, goes on the right axis, from 0 to 100%, as
dashed lines with hollow markers, because a throughput number must never be
shown without what it cost. It also prints a table of the same numbers with
each transaction type's 90th percentile response time.

`timeline` is the graph TPC-C asks for in clause 5.6.5, throughput against
elapsed time: tpmC in every reporting interval from the moment the
connections start, with the ramp-up shaded. Every timeline file is one run
and all runs of an engine make one line, the mean, inside a band from the
slowest run to the fastest. A dashed line marks each engine's tpmC over the
measured window.

`response-time` is the graph TPC-C asks for in clause 5.6.1, the response
time frequency distribution: a panel per transaction type, the share of an
engine's transactions against their response time, from zero to four times
the slowest engine's 90th percentile, with a dashed line at each engine's
90th percentile. TPC-C counts transactions on the y axis; this figure
compares engines whose throughput differs, so it shows each engine's share
instead. Every histogram file is one run, and an engine's runs are added
up.

`-o` can be given more than once, and each output's format follows its
extension: `.png`, `.pdf` and the other matplotlib formats draw the figure;
`.tikz` or `.tex` write a pgfplots picture for `\\input` into a LaTeX
document that loads pgfplots with its `groupplots` and `fillbetween`
libraries, TikZ's `calc` library and `\\pgfplotsset{compat=1.18}`.
"""

import argparse
import csv
import os
from pathlib import Path

import numpy as np

# The Okabe-Ito palette: colour-blind safe, legible in greyscale, and what
# gnuplot draws with by default. `tikz_marks` are the pgf names of the
# matplotlib `marker`, filled and hollow.
ENGINES = {
    "sqlite": {"name": "SQLite", "color": "#E69F00", "marker": "s", "tikz_marks": ("square*", "square")},
    "turso": {"name": "Turso", "color": "#0072B2", "marker": "o", "tikz_marks": ("*", "o")},
}
FALLBACK_COLORS = ["#009E73", "#D55E00", "#CC79A7"]
FALLBACK_MARKERS = [("^", ("triangle*", "triangle")), ("D", ("diamond*", "diamond")),
                    ("v", ("triangle*", "triangle"))]

TRANSACTIONS = [("neworder", "New-Order"), ("payment", "Payment"),
                ("orderstatus", "Order-Status"), ("delivery", "Delivery"),
                ("stocklevel", "Stock-Level")]

TIKZ_HEADER = "% Generated by perf/tpc-c/plot/plot-tpcc.py. Do not edit."
TIKZ_AXIS_STYLE = (r"tick label style={font=\scriptsize}, label style={font=\footnotesize}, "
                   r"axis line style={line width=0.4pt}, tick style={line width=0.4pt, black}, "
                   r"yticklabel style={/pgf/number format/1000 sep={}}")
TIKZ_GRID = r"grid=major, grid style={line width=0.3pt, dashed, draw=black!30}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("figure", choices=["tpmc", "timeline", "response-time"])
    parser.add_argument("csv_files", nargs="+", type=Path)
    parser.add_argument("-o", "--output", action="append", type=Path, metavar="FILE",
                        help="output file; repeat for several formats "
                             "(default <figure>.png)")
    parser.add_argument("--name", action="append", default=[], metavar="ENGINE=NAME",
                        help="legend name for an engine, e.g. turso=Limbo")
    args = parser.parse_args()
    names = dict(name.split("=", 1) for name in args.name)

    rows = []
    for path in args.csv_files:
        with open(path, newline="") as f:
            rows.extend((path, row) for row in csv.DictReader(f))
    if not rows:
        raise SystemExit("no results found")
    figure = {"tpmc": TpmcFigure, "timeline": TimelineFigure,
              "response-time": ResponseTimeFigure}[args.figure](rows, names)

    for output in args.output or [Path(f"{args.figure}.png")]:
        if output.suffix in (".tikz", ".tex"):
            output.write_text(figure.tikz())
        else:
            figure.matplotlib(output)
        print(f"wrote {output}")


class Style:
    """How one engine is drawn, the same in every figure."""

    def __init__(self, engine, index, name=None):
        look = ENGINES.get(engine)
        self.engine = engine
        self.label = name or (look["name"] if look else engine)
        if look:
            self.color, self.marker, self.tikz_marks = look["color"], look["marker"], look["tikz_marks"]
        else:
            self.color = FALLBACK_COLORS[index % len(FALLBACK_COLORS)]
            self.marker, self.tikz_marks = FALLBACK_MARKERS[index % len(FALLBACK_MARKERS)]
        self.tikz_color = "".join(ch for ch in engine if ch.isalpha())


def styles(engines, names):
    return [Style(e, i, names.get(e)) for i, e in enumerate(sorted(engines))]


def mean_sd(values):
    return float(np.mean(values)), float(np.std(values)) if len(values) > 1 else 0.0


def setup_matplotlib():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import scienceplots  # noqa: F401  (registers the styles)

    plt.style.use(["science", "no-latex"])
    return plt


def legend_below(fig, ax, styles, extra=(), y=-0.2):
    from matplotlib.lines import Line2D

    handles = [Line2D([], [], color=s.color, linestyle="none", marker=s.marker,
                      markersize=4.5, label=s.label) for s in styles]
    handles.extend(extra)
    fig.legend(handles=handles, loc="upper center", ncol=len(handles), frameon=False,
               handlelength=1.4, handletextpad=0.4, columnspacing=1.8,
               bbox_transform=ax.transAxes, bbox_to_anchor=(0.5, y))


def tikz_legend(styles, name):
    """A legend built on one axis, to be placed under the picture by name."""
    out = [rf"legend columns=-1, legend to name={name},",
           r"legend style={draw=none, font=\scriptsize, /tikz/every even column/.append style={column sep=0.5cm}},"]
    entries = []
    for s in styles:
        entries.append(rf"\addlegendimage{{only marks, {s.tikz_color}, mark={s.tikz_marks[0]}, mark size=1.6pt}}")
        entries.append(rf"\addlegendentry{{{s.label}}}")
    return "\n  ".join(out), entries


def tikz_colors(styles):
    return [rf"\definecolor{{{s.tikz_color}}}{{HTML}}{{{s.color.lstrip('#')}}}" for s in styles]


class TpmcFigure:
    """tpmC and CPU against connections, one line per engine for each."""

    class Run:
        def __init__(self, row):
            self.tpmc = float(row["tpmc"])
            busy = float(row["cpu_user_s"]) + float(row["cpu_sys_s"])
            threads = int(row.get("hardware_threads") or os.cpu_count() or 1)
            self.cpu_percent = busy / float(row["seconds"]) / threads * 100.0
            self.p90 = {t: float(row[f"{t}_p90_rt_ms"]) for t, _ in TRANSACTIONS}

    def __init__(self, rows, names):
        runs = {}
        for _, row in rows:
            runs.setdefault((row["engine"], int(row["connections"])), []).append(self.Run(row))
        self.connections = sorted({c for _, c in runs})
        self.series = []
        for s in styles({e for e, _ in runs}, names):
            mine = sorted(((c, v) for (e, c), v in runs.items() if e == s.engine), key=lambda kv: kv[0])
            s.tpmc = [(c, *mean_sd([r.tpmc for r in v])) for c, v in mine]
            s.cpu = [(c, *mean_sd([r.cpu_percent for r in v])) for c, v in mine]
            s.runs = mine
            self.series.append(s)
        self.tpmc_top = max(m + sd for s in self.series for _, m, sd in s.tpmc)
        self.cpu_top = max(m + sd for s in self.series for _, m, sd in s.cpu)
        self.ymax = self.tpmc_top * 1.15
        self.print_table()

    def print_table(self):
        head = ["engine", "conns", "runs", "tpmC", "sd", "cpu%"] + [f"{n} p90 ms" for _, n in TRANSACTIONS]
        lines = [head]
        for s in self.series:
            for c, v in s.runs:
                tpmc, sd = mean_sd([r.tpmc for r in v])
                cpu, _ = mean_sd([r.cpu_percent for r in v])
                lines.append([s.label, str(c), str(len(v)), f"{tpmc:.0f}", f"{sd:.0f}", f"{cpu:.1f}"]
                             + [f"{np.mean([r.p90[t] for r in v]):.3f}" for t, _ in TRANSACTIONS])
        widths = [max(len(line[i]) for line in lines) for i in range(len(head))]
        for line in lines:
            print("  ".join(cell.rjust(w) for cell, w in zip(line, widths)))

    def matplotlib(self, output):
        plt = setup_matplotlib()
        from matplotlib.lines import Line2D
        from matplotlib.offsetbox import AnnotationBbox, DrawingArea, HPacker, TextArea
        from matplotlib.ticker import FuncFormatter, NullLocator

        fig, ax = plt.subplots(figsize=(3.8, 2.6), dpi=300)
        ax.set_xscale("log", base=2)
        ax.grid(True, which="major", linewidth=0.5, linestyle=(0, (2, 2)), color="0.7")
        ax.set_axisbelow(True)
        cpu_ax = ax.twinx()
        for s in self.series:
            ax.errorbar([c for c, _, _ in s.tpmc], [m for _, m, _ in s.tpmc],
                        yerr=[sd for _, _, sd in s.tpmc], color=s.color, linewidth=1.3,
                        marker=s.marker, markersize=4.5, capsize=2.5, elinewidth=0.9,
                        zorder=3)
            cpu_ax.errorbar([c for c, _, _ in s.cpu], [m for _, m, _ in s.cpu],
                            yerr=[sd for _, _, sd in s.cpu], color=s.color, linewidth=1.1,
                            linestyle=(0, (4, 2)), marker=s.marker, markersize=4.5,
                            markerfacecolor="white", capsize=2.5, elinewidth=0.9, zorder=3)
        ax.set_xticks(self.connections)
        ax.xaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{v:g}"))
        ax.xaxis.set_minor_locator(NullLocator())
        ax.set_xlim(self.connections[0] / 1.5, self.connections[-1] * 1.5)
        ax.set_ylim(0, self.ymax)
        ax.yaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{v:g}"))
        ax.set_xlabel("Connections")
        ax.set_ylabel("New-Order transactions per minute (tpmC)")
        cpu_ax.set_ylim(0, 100)
        cpu_ax.set_yticks([0, 25, 50, 75, 100])
        cpu_ax.yaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{v:g}"))
        cpu_ax.yaxis.set_minor_locator(NullLocator())
        cpu_ax.set_ylabel("CPU utilization (%)")

        # Each group of lines gets a label above its right end, shifted left
        # off the last marker, led by a sample of the group's line style.
        def group_label(axis, y, text, linestyle):
            sample = DrawingArea(14, 6, 0, 0)
            sample.add_artist(Line2D([0, 14], [3, 3], color="0.4", linewidth=1.2, linestyle=linestyle))
            label = HPacker(children=[sample, TextArea(text, textprops={"color": "0.4", "size": 7})],
                            align="center", pad=0, sep=3)
            axis.add_artist(AnnotationBbox(label, (self.connections[-1], y), xybox=(-10, 4),
                                           boxcoords="offset points", box_alignment=(1, 0),
                                           frameon=False, pad=0))

        group_label(ax, self.tpmc_top, "tpmC", "-")
        group_label(cpu_ax, self.cpu_top, "CPU", (0, (4, 2)))
        legend_below(fig, ax, self.series)
        fig.savefig(output, bbox_inches="tight")

    def tikz(self):
        out = [TIKZ_HEADER, r"\begin{tikzpicture}", *tikz_colors(self.series)]
        xticks = ",".join(str(c) for c in self.connections)
        common = (rf"scale only axis, width=0.78\linewidth, height=0.5\linewidth, "
                  rf"xmode=log, log basis x=2, xmin={self.connections[0] / 1.5:g}, "
                  rf"xmax={self.connections[-1] * 1.5:g}, xtick={{{xticks}}}, "
                  rf"log ticks with fixed point, xminorticks=false, {TIKZ_AXIS_STYLE}, "
                  rf"error bars/y dir=both, error bars/y explicit, "
                  rf"error bars/error mark options={{line width=0.5pt, mark size=1.5pt, rotate=90}}")
        legend, entries = tikz_legend(self.series, "tpmclegend")
        # Two axes on top of each other: tpmC on the left, CPU on the right.
        out.append(rf"""\begin{{axis}}[
  name=tpmc, {common},
  ymin=0, ymax={self.ymax:.4g}, xlabel={{Connections}},
  ylabel={{New-Order transactions per minute (tpmC)}},
  {TIKZ_GRID}, axis y line*=left,
  {legend}
]""")
        out.extend(entries)
        for s in self.series:
            coords = " ".join(f"({c},{m:.4g}) +- (0,{sd:.4g})" for c, m, sd in s.tpmc)
            out.append(rf"\addplot[forget plot, {s.tikz_color}, line width=0.9pt, mark={s.tikz_marks[0]}, "
                       rf"mark size=1.6pt] coordinates {{{coords}}};")
        out.append(self.tikz_group_label(self.tpmc_top, "tpmC", ""))
        out.append(r"\end{axis}")
        out.append(rf"""\begin{{axis}}[
  at={{(tpmc.south west)}}, anchor=south west, {common},
  ymin=0, ymax=100, ytick={{0,25,50,75,100}},
  axis y line*=right, axis x line=none, ylabel={{CPU utilization (\%)}},
]""")
        for s in self.series:
            coords = " ".join(f"({c},{m:.4g}) +- (0,{sd:.4g})" for c, m, sd in s.cpu)
            out.append(rf"\addplot[{s.tikz_color}, line width=0.8pt, dashed, mark={s.tikz_marks[1]}, "
                       rf"mark size=1.6pt, mark options={{solid}}] coordinates {{{coords}}};")
        out.append(self.tikz_group_label(self.cpu_top, "CPU", "dashed, "))
        out.append(r"\end{axis}")
        out.append(r"\node[anchor=north] at ($(tpmc.south west)!0.5!(tpmc.south east) + (0,-0.9cm)$) "
                   r"{\pgfplotslegendfromname{tpmclegend}};")
        out.append(r"\end{tikzpicture}")
        return "\n".join(out) + "\n"

    def tikz_group_label(self, y, text, style):
        """A label above the right end of a group of lines, shifted left off
        the last marker, led by a sample of the group's line style."""
        return (rf"\node[anchor=south east, xshift=-10pt, yshift=3pt, font=\scriptsize, text=black!60] "
                rf"at (axis cs:{self.connections[-1]},{y:.4g}) "
                rf"{{\tikz[baseline=-0.5ex, x=1cm, y=1cm]"
                rf"\draw[black!60, line width=0.8pt, {style}] (0,0) -- (0.45,0); {text}}};")


class TimelineFigure:
    """tpmC in every reporting interval, ramp-up included, one line per
    engine: the mean over runs inside a band from the slowest to the
    fastest."""

    def __init__(self, rows, names):
        runs = {}
        for path, row in rows:
            runs.setdefault((row["engine"], path), []).append(row)
        self.rampup_end = 0.0
        # Every run of an engine must report at the same times; a run that
        # stops early is cut off, and one that starts late is an error.
        self.series = []
        for s in styles({e for e, _ in runs}, names):
            per_run = []
            for (e, _), mine in sorted(runs.items()):
                if e != s.engine:
                    continue
                elapsed = np.array([float(r["elapsed_s"]) for r in mine])
                widths = np.diff(elapsed, prepend=0.0)
                tpmc = np.array([int(r["neworder"]) for r in mine]) * 60.0 / widths
                measured = np.array([r["phase"] == "measure" for r in mine])
                self.rampup_end = max(self.rampup_end, float(elapsed[~measured].max(initial=0.0)))
                per_run.append((elapsed, tpmc, measured))
            n = min(len(e) for e, _, _ in per_run)
            for elapsed, _, _ in per_run:
                if not np.array_equal(elapsed[:n], per_run[0][0][:n]):
                    raise SystemExit(f"{s.engine}: runs report at different times")
            s.elapsed = per_run[0][0][:n]
            stack = np.array([t[:n] for _, t, _ in per_run])
            s.mean, s.low, s.high = stack.mean(axis=0), stack.min(axis=0), stack.max(axis=0)
            measured = per_run[0][2][:n]
            s.tpmc = float(stack[:, measured].mean())
            self.series.append(s)
        self.xmax = max(float(s.elapsed[-1]) for s in self.series)
        self.ymax = max(float(s.high.max()) for s in self.series) * 1.15

    def matplotlib(self, output):
        plt = setup_matplotlib()
        from matplotlib.lines import Line2D
        from matplotlib.ticker import FuncFormatter

        fig, ax = plt.subplots(figsize=(3.8, 2.4), dpi=300)
        ax.grid(True, which="major", linewidth=0.5, linestyle=(0, (2, 2)), color="0.7")
        ax.set_axisbelow(True)
        if self.rampup_end:
            ax.axvspan(0, self.rampup_end, color="0.92", zorder=0, linewidth=0)
            ax.text(self.rampup_end / 2, self.ymax * 0.97, "ramp-up", ha="center", va="top",
                    fontsize=6, color="0.4")
        for s in self.series:
            ax.fill_between(s.elapsed, s.low, s.high, color=s.color, alpha=0.2, linewidth=0)
            ax.plot(s.elapsed, s.mean, color=s.color, linewidth=1.1, zorder=3)
            ax.axhline(s.tpmc, color=s.color, linewidth=0.8, linestyle=(0, (4, 2)), zorder=2)
            ax.annotate(f"{s.tpmc:,.0f} tpmC", (self.xmax, s.tpmc), xytext=(-2, 2),
                        textcoords="offset points", ha="right", va="bottom", fontsize=6,
                        color=s.color)
        ax.set_xlim(0, self.xmax)
        ax.set_ylim(0, self.ymax)
        ax.yaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{v:g}"))
        ax.set_xlabel("Elapsed time (s)")
        ax.set_ylabel("tpmC")
        mean = Line2D([], [], color="0.4", linewidth=1.1, label="mean of runs")
        mark = Line2D([], [], color="0.4", linewidth=0.8, linestyle=(0, (4, 2)), label="measured tpmC")
        legend_below(fig, ax, self.series, extra=[mean, mark], y=-0.22)
        fig.savefig(output, bbox_inches="tight")

    def tikz(self):
        out = [TIKZ_HEADER, r"\begin{tikzpicture}", *tikz_colors(self.series)]
        legend, entries = tikz_legend(self.series, "timelinelegend")
        out.append(rf"""\begin{{axis}}[
  name=timeline, scale only axis, width=0.78\linewidth, height=0.45\linewidth,
  xmin=0, xmax={self.xmax:g}, ymin=0, ymax={self.ymax:.4g},
  xlabel={{Elapsed time (s)}}, ylabel={{tpmC}}, {TIKZ_AXIS_STYLE}, {TIKZ_GRID},
  {legend}
]""")
        out.extend(entries)
        out.append(r"\addlegendimage{black!60, line width=0.8pt}")
        out.append(r"\addlegendentry{mean of runs}")
        out.append(r"\addlegendimage{black!60, line width=0.6pt, dashed}")
        out.append(r"\addlegendentry{measured tpmC}")
        if self.rampup_end:
            out.append(rf"\fill[black!8] (axis cs:0,0) rectangle (axis cs:{self.rampup_end:g},{self.ymax:.4g});")
            out.append(rf"\node[anchor=north, font=\tiny, text=black!60] "
                       rf"at (axis cs:{self.rampup_end / 2:g},{self.ymax * 0.97:.4g}) {{ramp-up}};")
        for s in self.series:
            high = " ".join(f"({x:g},{y:.4g})" for x, y in zip(s.elapsed, s.high))
            low = " ".join(f"({x:g},{y:.4g})" for x, y in zip(s.elapsed, s.low))
            mean = " ".join(f"({x:g},{y:.4g})" for x, y in zip(s.elapsed, s.mean))
            out.append(rf"\addplot[forget plot, name path={s.tikz_color}high, draw=none] coordinates {{{high}}};")
            out.append(rf"\addplot[forget plot, name path={s.tikz_color}low, draw=none] coordinates {{{low}}};")
            out.append(rf"\addplot[forget plot, {s.tikz_color}, fill opacity=0.2] "
                       rf"fill between[of={s.tikz_color}high and {s.tikz_color}low];")
            out.append(rf"\addplot[forget plot, {s.tikz_color}, line width=0.8pt] coordinates {{{mean}}};")
            out.append(rf"\addplot[forget plot, {s.tikz_color}, line width=0.6pt, dashed] "
                       rf"coordinates {{(0,{s.tpmc:.4g}) ({self.xmax:g},{s.tpmc:.4g})}};")
            out.append(rf"\node[anchor=south east, font=\tiny, text={s.tikz_color}, inner sep=1pt] "
                       rf"at (axis cs:{self.xmax:g},{s.tpmc:.4g}) {{{s.tpmc:,.0f} tpmC}};")
        out.append(r"\end{axis}")
        out.append(r"\node[anchor=north] at ($(timeline.south west)!0.5!(timeline.south east) + (0,-0.9cm)$) "
                   r"{\pgfplotslegendfromname{timelinelegend}};")
        out.append(r"\end{tikzpicture}")
        return "\n".join(out) + "\n"


class ResponseTimeFigure:
    """A panel per transaction type: what share of an engine's
    transactions took how long, and each engine's 90th percentile."""

    BINS = 100

    def __init__(self, rows, names):
        counts = {}
        for _, row in rows:
            key = (row["engine"], row["transaction"])
            counts.setdefault(key, {})
            counts[key][float(row["rt_ms"])] = counts[key].get(float(row["rt_ms"]), 0) + int(row["count"])
        self.series = styles({e for e, _ in counts}, names)
        self.panels = []
        for t, name in TRANSACTIONS:
            panel = {"name": name, "engines": []}
            for s in self.series:
                buckets = counts.get((s.engine, t), {})
                rt = np.array(sorted(buckets))
                n = np.array([buckets[x] for x in rt], dtype=float)
                n *= 100.0 / max(n.sum(), 1.0)
                panel["engines"].append((s, rt, n, percentile(rt, n, 90)))
            xmax = 4 * max(p90 for _, _, _, p90 in panel["engines"])
            edges = np.linspace(0, xmax, self.BINS + 1)
            for s, rt, n, p90 in panel["engines"]:
                # A bucket sits at its lower edge; transactions past the
                # right edge are off the chart, as in a TPC-C report.
                inside = rt < xmax
                hist, _ = np.histogram(rt[inside], bins=edges, weights=n[inside])
                panel.setdefault("hist", []).append((s, hist, p90))
            panel["edges"] = edges
            panel["ymax"] = max(h.max() for _, h, _ in panel["hist"]) * 1.1
            self.panels.append(panel)

    def matplotlib(self, output):
        plt = setup_matplotlib()
        from matplotlib.lines import Line2D
        from matplotlib.ticker import FuncFormatter

        fig, axes = plt.subplots(2, 3, figsize=(7.2, 4.0), dpi=300)
        for ax, panel in zip(axes.flat, self.panels):
            ax.grid(True, which="major", linewidth=0.5, linestyle=(0, (2, 2)), color="0.7")
            ax.set_axisbelow(True)
            edges = panel["edges"]
            for s, hist, p90 in panel["hist"]:
                ax.stairs(hist, edges, fill=True, color=s.color, alpha=0.25, linewidth=0)
                ax.stairs(hist, edges, color=s.color, linewidth=0.9, zorder=3)
                ax.axvline(p90, color=s.color, linewidth=0.8, linestyle=(0, (4, 2)), zorder=2)
            ax.set_xlim(0, edges[-1])
            ax.set_ylim(0, panel["ymax"])
            ax.xaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{v:g}"))
            ax.yaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{v:g}"))
            ax.set_title(panel["name"], fontsize=8)
            ax.set_xlabel("Response time (ms)")
            ax.set_ylabel("Share of transactions (%)")
            for i, (s, _, p90) in enumerate(panel["hist"]):
                ax.text(0.97, 0.95 - 0.09 * i, f"{s.label} 90th: {p90:g} ms", transform=ax.transAxes,
                        ha="right", va="top", fontsize=5.5, color=s.color, zorder=4,
                        bbox={"facecolor": "white", "edgecolor": "none", "pad": 1})
        axes.flat[-1].axis("off")
        handles = [Line2D([], [], color=s.color, linewidth=6, alpha=0.4, label=s.label) for s in self.series]
        handles.append(Line2D([], [], color="0.4", linewidth=0.8, linestyle=(0, (4, 2)),
                              label="90th percentile"))
        axes.flat[-1].legend(handles=handles, loc="center", frameon=False, handlelength=1.6,
                             handletextpad=0.5, labelspacing=0.8)
        fig.tight_layout(w_pad=1.2, h_pad=1.5)
        fig.savefig(output, bbox_inches="tight")

    def tikz(self):
        out = [TIKZ_HEADER, r"\begin{tikzpicture}", *tikz_colors(self.series)]
        out.append(rf"""\begin{{groupplot}}[
  group style={{group size=3 by 2, horizontal sep=1.4cm, vertical sep=1.6cm}},
  scale only axis, width=0.24\linewidth, height=0.18\linewidth,
  xlabel={{Response time (ms)}}, ylabel={{Share of transactions (\%)}}, ymin=0,
  title style={{font=\footnotesize, yshift=-3pt}}, {TIKZ_AXIS_STYLE}, {TIKZ_GRID},
  legend columns=-1, legend to name=responselegend,
  legend style={{draw=none, font=\scriptsize, /tikz/every even column/.append style={{column sep=0.5cm}}}},
]""")
        for panel in self.panels:
            edges = panel["edges"]
            out.append(rf"\nextgroupplot[title={{{panel['name']}}}, xmin=0, xmax={edges[-1]:.4g}, ymax={panel['ymax']:.4g}]")
            for s, hist, p90 in panel["hist"]:
                # const plot draws each value from its coordinate to the
                # next, so the last edge closes the final bin at zero.
                coords = " ".join(f"({x:.4g},{y:.4g})" for x, y in zip(edges, [*hist, 0.0]))
                out.append(rf"\addplot[forget plot, const plot, draw=none, fill={s.tikz_color}, fill opacity=0.25] "
                           rf"coordinates {{{coords}}} \closedcycle;")
                out.append(rf"\addplot[forget plot, const plot, {s.tikz_color}, line width=0.6pt] coordinates {{{coords}}};")
                out.append(rf"\addplot[forget plot, {s.tikz_color}, line width=0.6pt, dashed] "
                           rf"coordinates {{({p90:.4g},0) ({p90:.4g},{panel['ymax']:.4g})}};")
            for i, (s, _, p90) in enumerate(panel["hist"]):
                out.append(rf"\node[anchor=north east, font=\tiny, text={s.tikz_color}, inner sep=1pt, fill=white] "
                           rf"at (rel axis cs:0.97,{0.95 - 0.1 * i:g}) {{{s.label} 90th: {p90:g}\,ms}};")
        out.append(r"\nextgroupplot[hide axis, xmin=0, xmax=1, ymin=0, ymax=1]")
        for s in self.series:
            out.append(rf"\addlegendimage{{area legend, fill={s.tikz_color}, fill opacity=0.4, draw={s.tikz_color}}}")
            out.append(rf"\addlegendentry{{{s.label}}}")
        out.append(r"\addlegendimage{black!60, line width=0.6pt, dashed}")
        out.append(r"\addlegendentry{90th percentile}")
        out.append(r"\end{groupplot}")
        out.append(r"\node at ($(group c3r2.north west)!0.5!(group c3r2.south east)$) "
                   r"{\pgfplotslegendfromname{responselegend}};")
        out.append(r"\end{tikzpicture}")
        return "\n".join(out) + "\n"


def percentile(rt, n, percent):
    """The bucket where the running count passes the percentile; a bucket
    is named by its lower edge, so the answer is the bucket after it."""
    if n.sum() == 0:
        return 0.0
    seen = np.cumsum(n)
    i = int(np.searchsorted(seen, n.sum() * percent / 100.0))
    return float(rt[i] + 0.01)


if __name__ == "__main__":
    main()
