// Generated by package:ffigen from ../c/include/sqlite3.h. Do not edit.
// ignore_for_file: type=lint, unused_field, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:turso/src/bindings.g.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Int)>()
external ffi.Pointer<ffi.Void> sqlite3_aggregate_context(
  ffi.Pointer<ffi.Void> _context,
  int _n,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int sqlite3_backup_finish(
  ffi.Pointer<ffi.Void> _backup,
);

@ffi.Native<
    ffi.Pointer<ffi.Void> Function(ffi.Pointer<sqlite3>, ffi.Pointer<ffi.Char>,
        ffi.Pointer<sqlite3>, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Void> sqlite3_backup_init(
  ffi.Pointer<sqlite3> _dest_db,
  ffi.Pointer<ffi.Char> _dest_name,
  ffi.Pointer<sqlite3> _source_db,
  ffi.Pointer<ffi.Char> _source_name,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int sqlite3_backup_pagecount(
  ffi.Pointer<ffi.Void> _backup,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int sqlite3_backup_remaining(
  ffi.Pointer<ffi.Void> _backup,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Int)>()
external int sqlite3_backup_step(
  ffi.Pointer<ffi.Void> _backup,
  int _n_pages,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<sqlite3_stmt>, ffi.Int, ffi.Pointer<ffi.Void>,
        ffi.Int, ffi.Pointer<ffi.Void>)>()
external int sqlite3_bind_blob(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
  ffi.Pointer<ffi.Void> _blob,
  int _len,
  ffi.Pointer<ffi.Void> _destroy,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>, ffi.Int, ffi.Double)>()
external int sqlite3_bind_double(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
  double _val,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>, ffi.Int, ffi.Int64)>()
external int sqlite3_bind_int64(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
  int _val,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external int sqlite3_bind_null(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>)>()
external int sqlite3_bind_parameter_count(
  ffi.Pointer<sqlite3_stmt> _stmt,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<sqlite3_stmt>, ffi.Pointer<ffi.Char>)>()
external int sqlite3_bind_parameter_index(
  ffi.Pointer<sqlite3_stmt> _stmt,
  ffi.Pointer<ffi.Char> _name,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external ffi.Pointer<ffi.Char> sqlite3_bind_parameter_name(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<sqlite3_stmt>, ffi.Int, ffi.Pointer<ffi.Char>,
        ffi.Int, ffi.Pointer<ffi.Void>)>()
external int sqlite3_bind_text(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
  ffi.Pointer<ffi.Char> _text,
  int _len,
  ffi.Pointer<ffi.Void> _destroy,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int sqlite3_blob_bytes(
  ffi.Pointer<ffi.Void> _blob,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int sqlite3_blob_close(
  ffi.Pointer<ffi.Void> _blob,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<sqlite3>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Int64,
        ffi.Int,
        ffi.Pointer<ffi.Pointer<ffi.Void>>)>()
external int sqlite3_blob_open(
  ffi.Pointer<sqlite3> _db,
  ffi.Pointer<ffi.Char> _db_name,
  ffi.Pointer<ffi.Char> _table_name,
  ffi.Pointer<ffi.Char> _column_name,
  int _rowid,
  int _flags,
  ffi.Pointer<ffi.Pointer<ffi.Void>> _blob_out,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Int, ffi.Int)>()
external int sqlite3_blob_read(
  ffi.Pointer<ffi.Void> _blob,
  ffi.Pointer<ffi.Void> _data,
  int _n,
  int _offset,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Int, ffi.Int)>()
external int sqlite3_blob_write(
  ffi.Pointer<ffi.Void> _blob,
  ffi.Pointer<ffi.Void> _data,
  int _n,
  int _offset,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>, ffi.Int)>()
external int sqlite3_busy_timeout(
  ffi.Pointer<sqlite3> _db,
  int _ms,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>)>()
external int sqlite3_changes(
  ffi.Pointer<sqlite3> _db,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<sqlite3>)>()
external int sqlite3_changes64(
  ffi.Pointer<sqlite3> _db,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>)>()
external int sqlite3_clear_bindings(
  ffi.Pointer<sqlite3_stmt> stmt,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>)>()
external int sqlite3_close(
  ffi.Pointer<sqlite3> db,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>)>()
external int sqlite3_close_v2(
  ffi.Pointer<sqlite3> db,
);

@ffi.Native<
    ffi.Pointer<ffi.Void> Function(ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external ffi.Pointer<ffi.Void> sqlite3_column_blob(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external int sqlite3_column_bytes(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>)>()
external int sqlite3_column_count(
  ffi.Pointer<sqlite3_stmt> _stmt,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external ffi.Pointer<ffi.Char> sqlite3_column_decltype(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
);

@ffi.Native<ffi.Double Function(ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external double sqlite3_column_double(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external int sqlite3_column_int64(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external ffi.Pointer<ffi.Char> sqlite3_column_name(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external ffi.Pointer<ffi.Char> sqlite3_column_table_name(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
);

@ffi.Native<
    ffi.Pointer<ffi.UnsignedChar> Function(
        ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external ffi.Pointer<ffi.UnsignedChar> sqlite3_column_text(
  ffi.Pointer<sqlite3_stmt> stmt,
  int idx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external int sqlite3_column_type(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
);

@ffi.Native<
    ffi.Pointer<ffi.Void> Function(ffi.Pointer<sqlite3_stmt>, ffi.Int)>()
external ffi.Pointer<ffi.Void> sqlite3_column_value(
  ffi.Pointer<sqlite3_stmt> _stmt,
  int _idx,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int sqlite3_complete(
  ffi.Pointer<ffi.Char> _sql,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<ffi.Void> sqlite3_context_db_handle(
  ffi.Pointer<ffi.Void> _context,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<sqlite3>,
        ffi.Pointer<ffi.Char>,
        ffi.Int,
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.NativeFunction<ffi.Int Function()>>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)>()
external int sqlite3_create_collation_v2(
  ffi.Pointer<sqlite3> _db,
  ffi.Pointer<ffi.Char> _name,
  int _enc,
  ffi.Pointer<ffi.Void> _context,
  ffi.Pointer<ffi.NativeFunction<ffi.Int Function()>> _cmp,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _destroy,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<sqlite3>,
        ffi.Pointer<ffi.Char>,
        ffi.Int,
        ffi.Int,
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)>()
external int sqlite3_create_function_v2(
  ffi.Pointer<sqlite3> _db,
  ffi.Pointer<ffi.Char> _name,
  int _n_args,
  int _enc,
  ffi.Pointer<ffi.Void> _context,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _func,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _step,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _final_,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _destroy,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<sqlite3>,
        ffi.Pointer<ffi.Char>,
        ffi.Int,
        ffi.Int,
        ffi.Pointer<ffi.Void>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>,
        ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)>()
external int sqlite3_create_window_function(
  ffi.Pointer<sqlite3> _db,
  ffi.Pointer<ffi.Char> _name,
  int _n_args,
  int _enc,
  ffi.Pointer<ffi.Void> _context,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _x_step,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _x_final,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _x_value,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _x_inverse,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> _destroy,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>)>()
external int sqlite3_data_count(
  ffi.Pointer<sqlite3_stmt> stmt,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>, ffi.Int)>()
external int sqlite3_db_config(
  ffi.Pointer<sqlite3> db,
  int op,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(
        ffi.Pointer<sqlite3>, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> sqlite3_db_filename(
  ffi.Pointer<sqlite3> db,
  ffi.Pointer<ffi.Char> db_name,
);

@ffi.Native<ffi.Pointer<sqlite3> Function(ffi.Pointer<sqlite3_stmt>)>()
external ffi.Pointer<sqlite3> sqlite3_db_handle(
  ffi.Pointer<sqlite3_stmt> _stmt,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<sqlite3>, ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Void>, ffi.Int, ffi.UnsignedInt)>()
external int sqlite3_deserialize(
  ffi.Pointer<sqlite3> _db,
  ffi.Pointer<ffi.Char> _schema,
  ffi.Pointer<ffi.Void> _in_,
  int _in_bytes,
  int _flags,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>)>()
external int sqlite3_errcode(
  ffi.Pointer<sqlite3> _db,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<sqlite3>)>()
external ffi.Pointer<ffi.Char> sqlite3_errmsg(
  ffi.Pointer<sqlite3> _db,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>()
external ffi.Pointer<ffi.Char> sqlite3_errstr(
  int _err,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<sqlite3>, ffi.Pointer<ffi.Char>, exec_callback,
        ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int sqlite3_exec(
  ffi.Pointer<sqlite3> db,
  ffi.Pointer<ffi.Char> sql,
  exec_callback _callback,
  ffi.Pointer<ffi.Void> _context,
  ffi.Pointer<ffi.Pointer<ffi.Char>> _err,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<sqlite3_stmt>)>()
external ffi.Pointer<ffi.Char> sqlite3_expanded_sql(
  ffi.Pointer<sqlite3_stmt> stmt,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>)>()
external int sqlite3_extended_errcode(
  ffi.Pointer<sqlite3> _db,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>, ffi.Int)>()
external int sqlite3_extended_result_codes(
  ffi.Pointer<sqlite3> db,
  int onoff,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>)>()
external int sqlite3_finalize(
  ffi.Pointer<sqlite3_stmt> stmt,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void sqlite3_free(
  ffi.Pointer<ffi.Void> _ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external void sqlite3_free_table(
  ffi.Pointer<ffi.Pointer<ffi.Char>> az_result,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>)>()
external int sqlite3_get_autocommit(
  ffi.Pointer<sqlite3> _db,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<sqlite3>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
        ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int sqlite3_get_table(
  ffi.Pointer<sqlite3> db,
  ffi.Pointer<ffi.Char> sql,
  ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> paz_result,
  ffi.Pointer<ffi.Int> pn_row,
  ffi.Pointer<ffi.Int> pn_column,
  ffi.Pointer<ffi.Pointer<ffi.Char>> pz_err_msg,
);

@ffi.Native<ffi.Int Function()>()
external int sqlite3_initialize();

@ffi.Native<ffi.Void Function(ffi.Pointer<sqlite3>)>()
external void sqlite3_interrupt(
  ffi.Pointer<sqlite3> _db,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<sqlite3>)>()
external int sqlite3_last_insert_rowid(
  ffi.Pointer<sqlite3> _db,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> sqlite3_libversion();

@ffi.Native<ffi.Int Function()>()
external int sqlite3_libversion_number();

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>, ffi.Int, ffi.Int)>()
external int sqlite3_limit(
  ffi.Pointer<sqlite3> _db,
  int _id,
  int _new_value,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Int)>()
external ffi.Pointer<ffi.Void> sqlite3_malloc64(
  int _n,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> sqlite3_mprintf(
  ffi.Pointer<ffi.Char> fmt,
);

@ffi.Native<
    ffi.Pointer<sqlite3_stmt> Function(
        ffi.Pointer<sqlite3>, ffi.Pointer<sqlite3_stmt>)>()
external ffi.Pointer<sqlite3_stmt> sqlite3_next_stmt(
  ffi.Pointer<sqlite3> db,
  ffi.Pointer<sqlite3_stmt> stmt,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<sqlite3>>)>()
external int sqlite3_open(
  ffi.Pointer<ffi.Char> filename,
  ffi.Pointer<ffi.Pointer<sqlite3>> db_out,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<sqlite3>>,
        ffi.Int, ffi.Pointer<ffi.Char>)>()
external int sqlite3_open_v2(
  ffi.Pointer<ffi.Char> filename,
  ffi.Pointer<ffi.Pointer<sqlite3>> db_out,
  int _flags,
  ffi.Pointer<ffi.Char> _z_vfs,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<sqlite3>,
        ffi.Pointer<ffi.Char>,
        ffi.Int,
        ffi.Pointer<ffi.Pointer<sqlite3_stmt>>,
        ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int sqlite3_prepare_v2(
  ffi.Pointer<sqlite3> db,
  ffi.Pointer<ffi.Char> sql,
  int _len,
  ffi.Pointer<ffi.Pointer<sqlite3_stmt>> out_stmt,
  ffi.Pointer<ffi.Pointer<ffi.Char>> _tail,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<sqlite3>,
        ffi.Pointer<ffi.Char>,
        ffi.Int,
        ffi.UnsignedInt,
        ffi.Pointer<ffi.Pointer<sqlite3_stmt>>,
        ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int sqlite3_prepare_v3(
  ffi.Pointer<sqlite3> db,
  ffi.Pointer<ffi.Char> sql,
  int _len,
  int _prep_flags,
  ffi.Pointer<ffi.Pointer<sqlite3_stmt>> out_stmt,
  ffi.Pointer<ffi.Pointer<ffi.Char>> _tail,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<sqlite3>,
        ffi.Int,
        ffi.Pointer<
            ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>)>>,
        ffi.Pointer<ffi.Void>)>()
external void sqlite3_progress_handler(
  ffi.Pointer<sqlite3> _db,
  int _n,
  ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>)>>
      _callback,
  ffi.Pointer<ffi.Void> _context,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>)>()
external int sqlite3_reset(
  ffi.Pointer<sqlite3_stmt> stmt,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>, ffi.Int,
        ffi.Pointer<ffi.Void>)>()
external void sqlite3_result_blob(
  ffi.Pointer<ffi.Void> _context,
  ffi.Pointer<ffi.Void> _blob,
  int _len,
  ffi.Pointer<ffi.Void> _destroy,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Double)>()
external void sqlite3_result_double(
  ffi.Pointer<ffi.Void> _context,
  double _val,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Int)>()
external void sqlite3_result_error(
  ffi.Pointer<ffi.Void> _context,
  ffi.Pointer<ffi.Char> _err,
  int _len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void sqlite3_result_error_nomem(
  ffi.Pointer<ffi.Void> _context,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void sqlite3_result_error_toobig(
  ffi.Pointer<ffi.Void> _context,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int)>()
external void sqlite3_result_int(
  ffi.Pointer<ffi.Void> _context,
  int _val,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int64)>()
external void sqlite3_result_int64(
  ffi.Pointer<ffi.Void> _context,
  int _val,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void sqlite3_result_null(
  ffi.Pointer<ffi.Void> _context,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Int,
        ffi.Pointer<ffi.Void>)>()
external void sqlite3_result_text(
  ffi.Pointer<ffi.Void> _context,
  ffi.Pointer<ffi.Char> _text,
  int _len,
  ffi.Pointer<ffi.Void> _destroy,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<sqlite3>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Pointer<ffi.Void>>,
        ffi.Pointer<ffi.Int>,
        ffi.UnsignedInt)>()
external int sqlite3_serialize(
  ffi.Pointer<sqlite3> _db,
  ffi.Pointer<ffi.Char> _schema,
  ffi.Pointer<ffi.Pointer<ffi.Void>> _out,
  ffi.Pointer<ffi.Int> _out_bytes,
  int _flags,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<sqlite3>,
        ffi.Pointer<
            ffi.NativeFunction<
                ffi.Int Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Int,
                    ffi.Pointer<ffi.Char>,
                    ffi.Pointer<ffi.Char>,
                    ffi.Pointer<ffi.Char>,
                    ffi.Pointer<ffi.Char>)>>,
        ffi.Pointer<ffi.Void>)>()
external int sqlite3_set_authorizer(
  ffi.Pointer<sqlite3> db,
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Int Function(
                  ffi.Pointer<ffi.Void>,
                  ffi.Int,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<ffi.Char>,
                  ffi.Pointer<ffi.Char>)>>
      xAuth,
  ffi.Pointer<ffi.Void> pUserData,
);

@ffi.Native<ffi.Int Function()>()
external int sqlite3_shutdown();

@ffi.Native<ffi.Void Function(ffi.Int)>()
external void sqlite3_sleep(
  int _ms,
);

@ffi.Native<
    ffi.Pointer<ffi.Char> Function(
        ffi.Int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> sqlite3_snprintf(
  int n,
  ffi.Pointer<ffi.Char> buf,
  ffi.Pointer<ffi.Char> fmt,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<sqlite3_stmt>)>()
external ffi.Pointer<ffi.Char> sqlite3_sql(
  ffi.Pointer<sqlite3_stmt> stmt,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>)>()
external int sqlite3_step(
  ffi.Pointer<sqlite3_stmt> stmt,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>)>()
external int sqlite3_stmt_busy(
  ffi.Pointer<sqlite3_stmt> _stmt,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>)>()
external int sqlite3_stmt_readonly(
  ffi.Pointer<sqlite3_stmt> _stmt,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3_stmt>, ffi.Int, ffi.Int)>()
external int sqlite3_stmt_status(
  ffi.Pointer<sqlite3_stmt> stmt,
  int op,
  int resetFlg,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external int sqlite3_stricmp(
  ffi.Pointer<ffi.Char> _a,
  ffi.Pointer<ffi.Char> _b,
);

/// Return meta information about a specific column of a database table.
///
/// @param db Connection handle
/// @param zDbName Database name or NULL for main database
/// @param zTableName Table name
/// @param zColumnName Column name
/// @param pzDataType OUTPUT: Declared data type
/// @param pzCollSeq OUTPUT: Collation sequence name
/// @param pNotNull OUTPUT: True if NOT NULL constraint exists
/// @param pPrimaryKey OUTPUT: True if column part of PK
/// @param pAutoinc OUTPUT: True if column is auto-increment
/// @return SQLITE_OK on success, SQLITE_ERROR on error
@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<sqlite3>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<ffi.Pointer<ffi.Char>>,
        ffi.Pointer<ffi.Pointer<ffi.Char>>,
        ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Int>)>()
external int sqlite3_table_column_metadata(
  ffi.Pointer<sqlite3> db,
  ffi.Pointer<ffi.Char> zDbName,
  ffi.Pointer<ffi.Char> zTableName,
  ffi.Pointer<ffi.Char> zColumnName,
  ffi.Pointer<ffi.Pointer<ffi.Char>> pzDataType,
  ffi.Pointer<ffi.Pointer<ffi.Char>> pzCollSeq,
  ffi.Pointer<ffi.Int> pNotNull,
  ffi.Pointer<ffi.Int> pPrimaryKey,
  ffi.Pointer<ffi.Int> pAutoinc,
);

@ffi.Native<ffi.Int Function()>()
external int sqlite3_threadsafe();

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>)>()
external int sqlite3_total_changes(
  ffi.Pointer<sqlite3> _db,
);

@ffi.Native<
    ffi.Int Function(
        ffi.Pointer<sqlite3>,
        ffi.UnsignedInt,
        ffi.Pointer<
            ffi.NativeFunction<
                ffi.Void Function(ffi.UnsignedInt, ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>,
        ffi.Pointer<ffi.Void>)>()
external int sqlite3_trace_v2(
  ffi.Pointer<sqlite3> _db,
  int _mask,
  ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(ffi.UnsignedInt, ffi.Pointer<ffi.Void>,
                  ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>
      _callback,
  ffi.Pointer<ffi.Void> _context,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<ffi.Void> sqlite3_user_data(
  ffi.Pointer<ffi.Void> _context,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<ffi.Void> sqlite3_value_blob(
  ffi.Pointer<ffi.Void> value,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int sqlite3_value_bytes(
  ffi.Pointer<ffi.Void> value,
);

@ffi.Native<ffi.Double Function(ffi.Pointer<ffi.Void>)>()
external double sqlite3_value_double(
  ffi.Pointer<ffi.Void> value,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<ffi.Void> sqlite3_value_dup(
  ffi.Pointer<ffi.Void> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void sqlite3_value_free(
  ffi.Pointer<ffi.Void> value,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int sqlite3_value_int(
  ffi.Pointer<ffi.Void> value,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<ffi.Void>)>()
external int sqlite3_value_int64(
  ffi.Pointer<ffi.Void> value,
);

@ffi.Native<ffi.Pointer<ffi.UnsignedChar> Function(ffi.Pointer<ffi.Void>)>()
external ffi.Pointer<ffi.UnsignedChar> sqlite3_value_text(
  ffi.Pointer<ffi.Void> value,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int sqlite3_value_type(
  ffi.Pointer<ffi.Void> value,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<sqlite3>, ffi.Pointer<ffi.Char>)>()
external int sqlite3_wal_checkpoint(
  ffi.Pointer<sqlite3> _db,
  ffi.Pointer<ffi.Char> _db_name,
);

@ffi.Native<
    ffi.Int Function(ffi.Pointer<sqlite3>, ffi.Pointer<ffi.Char>, ffi.Int,
        ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external int sqlite3_wal_checkpoint_v2(
  ffi.Pointer<sqlite3> db,
  ffi.Pointer<ffi.Char> _db_name,
  int _mode,
  ffi.Pointer<ffi.Int> _log_size,
  ffi.Pointer<ffi.Int> _checkpoint_count,
);

@ffi.Native<ffi.Void Function()>()
external void turso_enable_experimental();

const int SQLITE_ABORT = 4;

const int SQLITE_ABORT_ROLLBACK = 516;

const int SQLITE_ALTER_TABLE = 26;

const int SQLITE_ANALYZE = 28;

const int SQLITE_ATTACH = 24;

const int SQLITE_BLOB = 4;

const int SQLITE_BUSY = 5;

const int SQLITE_CANTOPEN = 14;

const int SQLITE_CHECKPOINT_FULL = 1;

const int SQLITE_CHECKPOINT_PASSIVE = 0;

const int SQLITE_CHECKPOINT_RESTART = 2;

const int SQLITE_CHECKPOINT_TRUNCATE = 3;

const int SQLITE_CONSTRAINT = 19;

const int SQLITE_COPY = 0;

const int SQLITE_CREATE_INDEX = 1;

const int SQLITE_CREATE_TABLE = 2;

const int SQLITE_CREATE_TEMP_INDEX = 3;

const int SQLITE_CREATE_TEMP_TABLE = 4;

const int SQLITE_CREATE_TEMP_TRIGGER = 5;

const int SQLITE_CREATE_TEMP_VIEW = 6;

const int SQLITE_CREATE_TRIGGER = 7;

const int SQLITE_CREATE_VIEW = 8;

const int SQLITE_CREATE_VTABLE = 29;

const int SQLITE_DBCONFIG_DEFENSIVE = 1010;

const int SQLITE_DBCONFIG_DQS_DDL = 1014;

const int SQLITE_DBCONFIG_DQS_DML = 1013;

const int SQLITE_DBCONFIG_ENABLE_FKEY = 1002;

const int SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER = 1004;

const int SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION = 1005;

const int SQLITE_DBCONFIG_ENABLE_QPSG = 1007;

const int SQLITE_DBCONFIG_ENABLE_TRIGGER = 1003;

const int SQLITE_DBCONFIG_ENABLE_VIEW = 1015;

const int SQLITE_DBCONFIG_LEGACY_ALTER_TABLE = 1012;

const int SQLITE_DBCONFIG_LEGACY_FILE_FORMAT = 1016;

const int SQLITE_DBCONFIG_LOOKASIDE = 1001;

const int SQLITE_DBCONFIG_MAINDBNAME = 1000;

const int SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE = 1006;

const int SQLITE_DBCONFIG_RESET_DATABASE = 1009;

const int SQLITE_DBCONFIG_TRIGGER_EQP = 1008;

const int SQLITE_DBCONFIG_TRUSTED_SCHEMA = 1017;

const int SQLITE_DBCONFIG_WRITABLE_SCHEMA = 1011;

const int SQLITE_DELETE = 9;

const int SQLITE_DENY = 1;

const int SQLITE_DETACH = 25;

const int SQLITE_DONE = 101;

const int SQLITE_DROP_INDEX = 10;

const int SQLITE_DROP_TABLE = 11;

const int SQLITE_DROP_TEMP_INDEX = 12;

const int SQLITE_DROP_TEMP_TABLE = 13;

const int SQLITE_DROP_TEMP_TRIGGER = 14;

const int SQLITE_DROP_TEMP_VIEW = 15;

const int SQLITE_DROP_TRIGGER = 16;

const int SQLITE_DROP_VIEW = 17;

const int SQLITE_DROP_VTABLE = 30;

const int SQLITE_ERROR = 1;

const int SQLITE_FLOAT = 2;

const int SQLITE_FUNCTION = 31;

const int SQLITE_IGNORE = 2;

const int SQLITE_INSERT = 18;

const int SQLITE_INTEGER = 1;

const int SQLITE_INTERRUPT = 9;

const int SQLITE_MISUSE = 21;

const int SQLITE_NOMEM = 7;

const int SQLITE_NOTFOUND = 12;

const int SQLITE_NULL = 5;

const int SQLITE_OK = 0;

const int SQLITE_PRAGMA = 19;

const int SQLITE_PREPARE_NORMALIZE = 2;

const int SQLITE_PREPARE_NO_VTAB = 4;

const int SQLITE_PREPARE_PERSISTENT = 1;

const int SQLITE_READ = 20;

const int SQLITE_RECURSIVE = 33;

const int SQLITE_REINDEX = 27;

const int SQLITE_ROW = 100;

const int SQLITE_SAVEPOINT = 32;

const int SQLITE_SELECT = 21;

const int SQLITE_STATE_BUSY = 109;

const int SQLITE_STATE_OPEN = 118;

const int SQLITE_STATE_SICK = 186;

const int SQLITE_STMTSTATUS_AUTOINDEX = 3;

const int SQLITE_STMTSTATUS_FILTER_HIT = 8;

const int SQLITE_STMTSTATUS_FILTER_MISS = 7;

const int SQLITE_STMTSTATUS_FULLSCAN_STEP = 1;

const int SQLITE_STMTSTATUS_MEMUSED = 99;

const int SQLITE_STMTSTATUS_REPREPARE = 5;

const int SQLITE_STMTSTATUS_RUN = 6;

const int SQLITE_STMTSTATUS_SORT = 2;

const int SQLITE_STMTSTATUS_VM_STEP = 4;

const int SQLITE_TEXT = 3;

const int SQLITE_TRANSACTION = 22;

const int SQLITE_UPDATE = 23;

typedef exec_callback = ffi.Pointer<ffi.NativeFunction<exec_callbackFunction>>;
typedef exec_callbackFunction = ffi.Int Function(
    ffi.Pointer<ffi.Void> context,
    ffi.Int n_column,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Pointer<ffi.Char>> colv);
typedef Dartexec_callbackFunction = int Function(
    ffi.Pointer<ffi.Void> context,
    int n_column,
    ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
    ffi.Pointer<ffi.Pointer<ffi.Char>> colv);

final class sqlite3 extends ffi.Opaque {}

typedef sqlite3_destructor_type
    = ffi.Pointer<ffi.NativeFunction<sqlite3_destructor_typeFunction>>;
typedef sqlite3_destructor_typeFunction = ffi.Void Function(
    ffi.Pointer<ffi.Void>);
typedef Dartsqlite3_destructor_typeFunction = void Function(
    ffi.Pointer<ffi.Void>);
typedef sqlite3_int64 = ffi.Int64;
typedef Dartsqlite3_int64 = int;

final class sqlite3_stmt extends ffi.Opaque {}

typedef sqlite_int64 = sqlite3_int64;
