name: Setup Bazel
description: Install the repository's Bazel version with Bazelisk

runs:
  using: composite
  steps:
    - uses: bazel-contrib/setup-bazel@0.19.0
      with:
        bazelisk-cache: true
