name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    timeout-minutes: 30
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
